#Auditions

audition = Audition.create!(name_of_company: "", theater_id: nil,  union_status: "Non-Equity", pay_scale: "", name_of_show: "", written_by: "", director: nil, musical_director: nil, choreographer: nil, rehearsal_startdate: "2023-08-23", tech_startdate: nil, previews_startdate: nil, show_startdate: "2023-10-13", show_enddate: "2023-10-28", show_address_id: nil, show_warnings: "", show_description: "", additional_notes: nil, audition_date1: "2023-08-20", audition_time1: nil, audition_date2: "2023-08-21", audition_time2: nil, audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: nil, callback_time1: nil, callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "", how_to_submit: "")

Character.create!(audition_id: audition.id, name: "", age: "", gender: "", ethnicity: "Any/Open", description: "", skills: "", notes: nil)
  

audition = Audition.create!(name_of_company: "AlphaBet Soup Productions", theater_id: nil,  union_status: "Non-Equity", pay_scale: "rehearsal stipend + per show pay", name_of_show: "Season 2023-2024", written_by: "", director: nil, musical_director: nil, choreographer: nil, rehearsal_startdate: nil, tech_startdate: nil, previews_startdate: nil, show_startdate: nil, show_enddate: nil, show_address_id: nil, show_warnings: "", show_description: "AlphaBet Soup Productions, Professional TYA, is seeking additional male actors for our 2023-24 Season! Productions include: Don't Let the Pigeon Drive the Bus (Oct-Jan), The Christmas That Almost Wasn't (Nov-Dec), James and the Giant Peach (Jan-Mar) and Alice in Wonderland (Apr-Jul). The majority of our performances are weekday mornings at 10:30am and occasional Saturdays, so daytime availability is a must. Having your own transportation is encouraged but not required. Shows typically rehearse for 8-10 days from 9a-3p at the ABS Production Office in Lombard. Performances will be held at various venues throughout the Chicagoland area including: Tivoli Theatre (Downers Grove), Jedlicka Performing Arts Center (Cicero), Philip Lynch Theatre (Romeoville), Menker Theatre (Palos Hills) etc.", additional_notes: nil, audition_date1: nil, audition_time1: nil, audition_date2: nil, audition_time2: nil, audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: nil, callback_time1: nil, callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "Please send headshot/resume and any performance reels", how_to_submit: "email casting@absproductions.com with headshot/resume and any performance reels")


audition = Audition.create!(name_of_company: "Pocket Theatre VR", theater_id: nil,  union_status: "Non-Equity", pay_scale: "$100 Stipend", name_of_show: "Innocent (Workshop)", written_by: "Genevieve Swanson", director: "Bridgette Martinez", musical_director: nil, choreographer: nil, rehearsal_startdate: "2023-10-01", tech_startdate: nil, previews_startdate: nil, show_startdate: "2023-11-17", show_enddate: "2023-11-17", show_address_id: nil, show_warnings: "", show_description: "Maggie, Miranda, and Mack have been best friends since kindergarten. They played Powerpuff Girls daily, fighting violent crime and demolishing their enemies. We meet them once again, now in their early twenties, getting drunk on Wine Wednesday, trying to navigate the world together. As the red continues to pour, a rant about late-stage capitalism in America turns murderous… “What happens if we actually eat the rich?”", additional_notes: "15 hours of rehearsal and one additional Zoom reading will take place during October, according to the availability of those involved. Rehearsals will take place in Lakeview, Chicago. There will be one performance on November 17th at Afterwords Bookstore", audition_date1: "2023-09-30", audition_time1: nil, audition_date2: nil, audition_time2: nil, audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: nil, callback_time1: nil, callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "send resume, headshot, and a video submission (reel and/or monologue)", how_to_submit: "pocket.vr.theatre@gmail.com")

Character.create!(audition_id: audition.id, name: "Miranda", age: "20s", gender: "Female", ethnicity: "Any/Open", description: "a blossoming leader", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Maggie", age: "20s", gender: "Female", ethnicity: "Any/Open", description: "a bubbly influencer", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Mack", age: "20s", gender: "Female", ethnicity: "Any/Open", description: "the edgy one", skills: "", notes: nil)


audition = Audition.create!(name_of_company: "Chicago Shakespeare Theater", theater_id: nil,  union_status: "Equity", pay_scale: "$600 - $700 weekly", name_of_show: "Short Shakes! Romeo & Juliet", written_by: "William Shakespeare", director: "Mikael Burke", musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-01-29", tech_startdate: nil, previews_startdate: "2024-02-22", show_startdate: "2024-02-24", show_enddate: "2024-03-20", show_address_id: nil, show_warnings: "", show_description: "SHORT SHAKESPEARE! ROMEO AND JULIET, a 75-minute adaptation followed by a 15-minute talkback that runs Monday – Friday during daytime hours for school students at CST, and for the public at 11 am on Saturdays. There is no tour to schools planned at this time.", additional_notes: nil, audition_date1: "", audition_time1: nil, audition_date2: "", audition_time2: nil, audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: nil, callback_time1: nil, callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: "", materials_to_prepare: "", how_to_submit: "")

Character.create!(audition_id: audition.id, name: "", age: "", gender: "", ethnicity: "Any/Open", description: "", skills: "", notes: nil)
