#Auditions

audition = Audition.create!(name_of_company: "", theater_id: nil,  union_status: "Non-Equity", pay_scale: "", name_of_show: "", written_by: "", director: nil, musical_director: nil, choreographer: nil, rehearsal_startdate: "2023-08-23", tech_startdate: nil, previews_startdate: nil, show_startdate: "2023-10-13", show_enddate: "2023-10-28", show_address_id: nil, show_warnings: "", show_description: "", additional_notes: nil, audition_date1: "2023-08-20", audition_time1: nil, audition_date2: "2023-08-21", audition_time2: nil, audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: nil, callback_time1: nil, callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "", how_to_submit: "")

Character.create!(audition_id: audition.id, name: "", age: "", gender: "", ethnicity: "Any/Open", description: "", skills: "", notes: nil)
  

audition = Audition.create!(name_of_company: "AlphaBet Soup Productions", theater_id: nil,  union_status: "Non-Equity", pay_scale: "rehearsal stipend + per show pay", name_of_show: "Season 2023-2024", written_by: "", director: nil, musical_director: nil, choreographer: nil, rehearsal_startdate: nil, tech_startdate: nil, previews_startdate: nil, show_startdate: nil, show_enddate: nil, show_address_id: nil, show_warnings: "", show_description: "AlphaBet Soup Productions, Professional TYA, is seeking additional male actors for our 2023-24 Season! Productions include: Don't Let the Pigeon Drive the Bus (Oct-Jan), The Christmas That Almost Wasn't (Nov-Dec), James and the Giant Peach (Jan-Mar) and Alice in Wonderland (Apr-Jul). The majority of our performances are weekday mornings at 10:30am and occasional Saturdays, so daytime availability is a must. Having your own transportation is encouraged but not required. Shows typically rehearse for 8-10 days from 9a-3p at the ABS Production Office in Lombard. Performances will be held at various venues throughout the Chicagoland area including: Tivoli Theatre (Downers Grove), Jedlicka Performing Arts Center (Cicero), Philip Lynch Theatre (Romeoville), Menker Theatre (Palos Hills) etc.", additional_notes: nil, audition_date1: nil, audition_time1: nil, audition_date2: nil, audition_time2: nil, audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: nil, callback_time1: nil, callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "Please send headshot/resume and any performance reels", how_to_submit: "email casting@absproductions.com with headshot/resume and any performance reels")


audition = Audition.create!(name_of_company: "Pocket Theatre VR", theater_id: nil,  union_status: "Non-Equity", pay_scale: "$100 Stipend", name_of_show: "Innocent (Workshop)", written_by: "Genevieve Swanson", director: "Bridgette Martinez", musical_director: nil, choreographer: nil, rehearsal_startdate: "2023-10-01", tech_startdate: nil, previews_startdate: nil, show_startdate: "2023-11-17", show_enddate: "2023-11-17", show_address_id: nil, show_warnings: "", show_description: "Maggie, Miranda, and Mack have been best friends since kindergarten. They played Powerpuff Girls daily, fighting violent crime and demolishing their enemies. We meet them once again, now in their early twenties, getting drunk on Wine Wednesday, trying to navigate the world together. As the red continues to pour, a rant about late-stage capitalism in America turns murderous… “What happens if we actually eat the rich?”", additional_notes: "15 hours of rehearsal and one additional Zoom reading will take place during October, according to the availability of those involved. Rehearsals will take place in Lakeview, Chicago. There will be one performance on November 17th at Afterwords Bookstore", audition_date1: "2023-09-30", audition_time1: nil, audition_date2: nil, audition_time2: nil, audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: nil, callback_time1: nil, callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "send resume, headshot, and a video submission (reel and/or monologue)", how_to_submit: "pocket.vr.theatre@gmail.com")

Character.create!(audition_id: audition.id, name: "Miranda", age: "20s", gender: "Female", ethnicity: "Any/Open", description: "a blossoming leader", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Maggie", age: "20s", gender: "Female", ethnicity: "Any/Open", description: "a bubbly influencer", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Mack", age: "20s", gender: "Female", ethnicity: "Any/Open", description: "the edgy one", skills: "", notes: nil)


audition = Audition.create!(name_of_company: "Chicago Shakespeare Theater", theater_id: nil,  union_status: "Equity", pay_scale: "$600 - $700 weekly", name_of_show: "Short Shakes! Romeo & Juliet", written_by: "William Shakespeare", director: "Mikael Burke", musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-01-29", tech_startdate: nil, previews_startdate: "2024-02-22", show_startdate: "2024-02-24", show_enddate: "2024-03-20", show_address_id: nil, show_warnings: "", show_description: "SHORT SHAKESPEARE! ROMEO AND JULIET, a 75-minute adaptation followed by a 15-minute talkback that runs Monday – Friday during daytime hours for school students at CST, and for the public at 11 am on Saturdays. There is no tour to schools planned at this time.", additional_notes: nil, audition_date1: "", audition_time1: nil, audition_date2: "", audition_time2: nil, audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: nil, callback_time1: nil, callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: "", materials_to_prepare: "Please prepare a Shakespeare monologue of choice, not to exceed 2 minutes. Please also share in your slate relevant experience/certification/skills as it relates to stage combat. This does not apply to Lord/Lady Capulet or the Friar.", how_to_submit: "Submit your tape here: https://forms.gle/sin38VdnCTBUkt9Y6")

Character.create!(audition_id: audition.id, name: "BENVOLIO", age: "20s", gender: "Male", ethnicity: "Open but especially seeking BIPOC", description: "Romeo’s cousin and friend. A peacekeeper and helper. Benevolent. Down to earth. Loyal to Romeo and the Montagues, but not afraid to defy them for the sake of peace. A rule-abider.", skills: "SAFD certified unarmed combat skills or the equivalent", notes: nil)
Character.create!(audition_id: audition.id, name: "LADY CAPULET", age: "30s-40s", gender: "Female", ethnicity: "Open but especially seeking BIPOC", description: "Wife of Capulet and Juliet’s mother. A trophy wife. Obsessed with keeping up appearances to please and appease the men in her life. Loves her daughter with a cool detachment and an icy grip. Like a show dog trainer, she has exceedingly high expectations and rewards obedience. Hates Montagues.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "LORD CAPULET", age: "30s-60s", gender: "Male", ethnicity: "Open but especially seeking BIPOC", description: "Head of the Capulet household. Juliet’s Father and Tybalt’s uncle.  The king of his own castle, who knows what’s best for everyone and acts accordingly. Fiercely protective and possessive of his house and name. Loves his family with a watchful eye and an iron fist. Like a domineering general, he demands complete submission and absolute respect. Hates Montagues.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "FRIAR LAURENCE", age: "60s", gender: "Male", ethnicity: "Open but especially seeking BIPOC", description: "The town friar. Romeo’s confidante and mentor. Honest and caring, insightful and sage, desires healing above all. Wants to repair the world, and will bend and break the rules in order to do so. A voice of reason in an unreasonable world, always seeking solutions. Believes in the power of love. The father Romeo lacks. ", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "MERCUTIO", age: "20s-30s", gender: "Male or Gender Non-Conforming", ethnicity: "Open but especially seeking BIPOC", description: "The Prince’s kinsman and best friend to Romeo. Both a lover and a fighter. Sex positive, queer af, intimidatingly self-assured. Witty and charming, brings the party wherever he goes, and will fight for his right to party when and how he pleases. Wild. Exuberant. Volatile. Makes his own rules.", skills: "Requires excellent fight skills (Rapier/dagger) and facility with language", notes: nil)


audition = Audition.create!(name_of_company: "Open Space Arts", theater_id: nil,  union_status: "Non-Equity", pay_scale: "$36 stipend", name_of_show: "The Last Jew – Table Read", written_by: "", director: nil, musical_director: nil, choreographer: nil, rehearsal_startdate: "", tech_startdate: nil, previews_startdate: nil, show_startdate: "", show_enddate: "", show_address_id: nil, show_warnings: "", show_description: "", additional_notes: nil, audition_date1: "", audition_time1: nil, audition_date2: "", audition_time2: nil, audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: nil, callback_time1: nil, callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "Submit Headshot, Resume, Cover Letter, and Reel with a contemporary monologue", how_to_submit: "Send all materials to openspacearts2022@gmail.com. In the subject line, please indicate your preferred role (actor, director, designer, crew, or creative) and mention staged readings to ensure that your application receives prompt attention.")

Character.create!(audition_id: audition.id, name: "Audrey", age: "30s", gender: "Female", ethnicity: "Any/Open", description: "culturally Jewish (knows Hebrew), lesbian, Yoga Accountant", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Neal", age: "20s", gender: "Male", ethnicity: "Any/Open", description: "Law and Order", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Mary", age: "30s", gender: "", ethnicity: "Any/Open", description: "Gardener, Nurse, Audrey’s wife", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Aatazaz", age: "30s", gender: "Male", ethnicity: "Any/Open", description: "Poet, Muslim, Gay", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Tribunal", age: "40s+", gender: "Male", ethnicity: "Any/Open", description: "Old, judge, closeted gay", skills: "", notes: nil)


audition = Audition.create!(name_of_company: "Blue in the Right Way", theater_id: nil,  union_status: "Non-Equity", pay_scale: "$800 Stipend", name_of_show: "WOMEN BEWARE WOMEN", written_by: "Thomas Middleton, freely adapted by Kevin V. Smith and Daiva Bhandari with Spanish translation by Sonia Perelló.", director: "Kevin V. Smith", musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-03-03", tech_startdate: "2024-04-22", previews_startdate: "2024-04-27", show_startdate: "2024-04-29", show_enddate: "2024-05-12", show_address_id: nil, show_warnings: "Incest, homophobia, transphobia, misogyny, sexual coercion, assault and violence", show_description: "Thomas Middleton’s 1621 psychosexual revenge tragedy tells the story of four women’s lives in the stranglehold of the patriarchy. In this queer feminist take, the lacerating personal narration of two surreal transfemme drag queens frames Middleton’s timeless tale, rushing it into the here and now. Our original English/Spanish adaptation dives deep, excavating the social frameworks of gender violence and the gender of violence, as the plot hurtles towards a devastating and outrageous new ending for our modern times.", additional_notes: "In reference to the character descriptions – most characters we encounter currently are on the binary and are written with he/him or she/her pronouns, and you will see that in the descriptions above. But however limiting the descriptions are, our casting seeks to be as inclusive as possible, and we invite gender non-conforming, genderqueer, transgender and non-binary actors to submit for the roles they most identify with. We will also list race/ethnicity when specific to the character but are otherwise seeking all races and ethnicities. In addition, we will list disabilities when specific to a character but are otherwise seeking actors with disabilities as well as non-disabled actors for all roles. (Source: Emily Tarquin, Kevin Kantor and Marilee Talkington).  All cast members must be fully vaccinated against COVID-19 in order to be cast in the show. “Fully vaccinated,” as defined by the CDC, is more than 14 calendar days following receipt of a final dose of an FDA or World Health Organization authorized or approved vaccine.", audition_date1: "2023-09-30", audition_time1: "10:00AM-5:00PM", audition_date2: "2023-10-02", audition_time2: "6:00PM-9:00PM", audition_date3: "2023-10-03", audition_time3: "6:00PM-9:00PM", audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: "2023-10-07", callback_time1: nil, callback_date2: "2023-10-08", callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "Please prepare the sides for the role for which you’d like to be considered. Sides and script are here: http://tinyurl.com/2ncwmx25", how_to_submit: "To submit for an audition date and time, please fill out this form: http://tinyurl.com/WBWAudSub")

Character.create!(audition_id: audition.id, name: "SOLANGE", age: "Open", gender: "Transfeminine", ethnicity: "Any/Open", description: "Transfeminine drag queen. Blistering, wistful, abstract-thinker, mystic, brave, surreal and poetic.", skills: "", notes: "")
Character.create!(audition_id: audition.id, name: "CLARA", age: "Open", gender: "Transfeminine", ethnicity: "Latine or Afro-Latine", description: "Transfeminine drag queen. Excoriating, insightful, verbal processor, funny, unflinching, surreal and poetic.", skills: "The actor playing this role should be a native Spanish speaker", notes: nil)
Character.create!(audition_id: audition.id, name: "BIANCA", age: "16", gender: "Female", ethnicity: "Black or Afro-Latine", description: "Wife to Leantio. Pure of heart, intelligent, intuitive, sarcastic, a force.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "LEANTIO", age: "22", gender: "Male", ethnicity: "Any/Open", description: "Husband to Bianca. A merchant. Athletic, cocky, philosophical, controlling, sex-obsessed", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "DUKE of Florence", age: "35-45", gender: "Male", ethnicity: "Any/Open", description: "Dictatorial. Socially graceful, appreciative, ruthless", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Leantio’s MOTHER", age: "60s", gender: "Female", ethnicity: "Any/Open", description: "A widow. Folksy, frank, convivial.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "ISABELLA", age: "16", gender: "Female", ethnicity: "Any/Open", description: "Daughter to Fabritio; niece to Livia and Hippolito. Sincere, contemplative, courageous, loyal", skills: "This role requires a strong singer (part of the audition will be to sing “Silver Dagger”)", notes: nil)
Character.create!(audition_id: audition.id, name: "WARD", age: "19", gender: "Male", ethnicity: "Any/Open", description: "A rich young heir. Grotesque, pompous, childlike, guileless.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "GUARDIANO", age: "39", gender: "Male", ethnicity: "Any/Open", description: "Guardian to the foolish Ward. Machiavellian, ambitious, refined, aloof", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "FABRITIO", age: "45", gender: "Male", ethnicity: "Caucasian", description: "Father to Isabella; brother to Livia and Hippolito. Dotty, daffy, boorish, sees in dollar signs", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "HIPPOLITO", age: "32", gender: "Male", ethnicity: "Caucasian", description: "Brother to Livia and Fabritio; uncle to Isabella. Soulful, tortured, devastatingly handsome, gentle, murderous", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "SORDIDO", age: "21", gender: "Male", ethnicity: "BIPOC", description: "The Ward’s Man. Mischievous, misogynistic, clever, spritely, a wordsmith.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Lord CARDINAL", age: "33-43", gender: "Male", ethnicity: "Any/Open", description: "Younger brother to the Duke. Fire and brimstone, true believer, closeted, patriarchal, depraved", skills: "", notes: nil)


audition = Audition.create!(name_of_company: "Madison Street Theater", theater_id: nil,  union_status: "Non-Equity", pay_scale: "$500 Stipend", name_of_show: "The Revolutionists", written_by: "Lauren Gunderson", director: "Rachel Pospisil", musical_director: nil, choreographer: nil, rehearsal_startdate: "", tech_startdate: "2023-10-30", previews_startdate: nil, show_startdate: "2023-11-03", show_enddate: "2023-11-12", show_address_id: nil, show_warnings: "", show_description: "", additional_notes: nil, audition_date1: "2023-09-215", audition_time1: nil, audition_date2: "", audition_time2: nil, audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: "2023-09-19", callback_time1: "6:00PM-10:00PM", callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "Submit Headshot, Resume, Cover Letter, and Video with a contemporary monologue under 2mins", how_to_submit: "Please share a submission folder to our Google Drive: info@madisonstreettheater.org Share link: https://drive.google.com/drive/folders/17oz5QiWx-hlDMNVcv2Ht8q97fa6Wx-3y?usp=sharing  Create a new folder and please use your name for the folder name. Upload a one to two-minute video with you performing a contemporary monologue. Include your headshot, resume, desired role, and a short note as to why you are interested in this project in your folder. Please include any conflicts to dates with your submission")

Character.create!(audition_id: audition.id, name: "Olympe de Gouges", age: "20s-40s", gender: "Female or Gender-Nonconforming", ethnicity: "Any/Open", description: "Older. Badass activist playwright and feminist", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Charlotte Corday", age: "20s-40s", gender: "Female or Gender-Nonconforming", ethnicity: "Any/Open", description: "Younger. Badass country girl and assassin", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Marie-Antoinette", age: "20s-40s", gender: "Female or Gender-Nonconforming", ethnicity: "Any/Open", description: "Older. Less badass but fascinating former queen of France", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Marianne Angelle", age: "20s-40s", gender: "Female or Gender-Nonconforming", ethnicity: "Any/Open", description: "Mid-aged. A badass black woman in Paris", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Swing", age: "20s-40s", gender: "Female or Gender-Nonconforming", ethnicity: "Any/Open", description: "Swing for all other roles", skills: "", notes: nil)


audition = Audition.create!(name_of_company: "The Factory Theater", theater_id: nil,  union_status: "Non-Equity", pay_scale: "$200 Stipend", name_of_show: "Party at the Pantheon", written_by: "Michael Jones", director: "Kamille Dawkins", musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-01-02", tech_startdate: "2024-02-04", previews_startdate: "2024-02-09", show_startdate: "2024-02-16", show_enddate: "2024-03-23", show_address_id: nil, show_warnings: "", show_description: "Orpheus is still big mad after his girlfriend, Eurydice, died. It wasn’t his fault. Good thing his friend, Dionysus, can throw a sick party. Hopefully Sisyphus can keep these two on speaking terms long enough for the disco ball to drop. Now all they gotta do is find some food, some drink, and some music for this thing. Peep them and a cast of characters straight out of English Class, in this modern take on the ancient classics.", additional_notes: nil, audition_date1: "2023-09-21", audition_time1: nil, audition_date2: "", audition_time2: nil, audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: "2024-09-28", callback_time1: "7:00PM-10:00PM", callback_date2: "2024-09-29", callback_time2: "7:00-10:00PM", callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "Submit headshot and resume. Sides will be provided via email", how_to_submit: "Email casting@thefactorytheater.com")

Character.create!(audition_id: audition.id, name: "Dionysus", age: "Open", gender: "Male or Gender-Nonconforming", ethnicity: "Black", description: "The God of Wine and Parties. Black. He/They. They're the life of the party. They also have a lot of love for their friends. Extrovert. Would probably be a good MC.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Orpheus", age: "Open", gender: "Male", ethnicity: "Black", description: "His girlfriend just died. Never without his lyre.* SadBoi. Black. He/Him. Orpheus is agood guy in a tough spot. Soft Spoken, dry humor. He just wants to be heard.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Sisyphus", age: "Open", gender: "Male", ethnicity: "Black", description: "", skills: "Always looking up(hill). (Former) Trickster. A Rock. Black. He/Him. Mad older brother vibes. Just a bit of a square, but still gonna clown around.", notes: nil)
Character.create!(audition_id: audition.id, name: "Chorus 1 (Cyclops, Artemis, Minotaur, Eurydice)", age: "Open", gender: "Open", ethnicity: "Black", description: "A Cyclops, and his Brother and Sister. Any Race., Artemis- Goddess of the Hunt. Over it. Any Race. She/They, The Minotaur- Tough Look, Soft Spoken. A Bull. He/Him, Eurydice- Black. Beautiful. Full of life. She/Her.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Chorus 2 (Persephone, Daedalus, Aries, The Oracle)-Any Pronouns", age: "Open", gender: "Open", ethnicity: "Non-White", description: "Persephone- Grandma incarnate. Warm. NonWhite. She/They, Daedalus- Makes a sick beat. Icarus’ producer/manager/dad. Non White. He/Him, Aries- God of War. kinda soft. Any Race. He/They, The Oracle- Celeb Podcaster. Any Race. She/Her", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Chorus 3 (Hades, Thesius, Hermes, Sister)", age: "Open", gender: "Open", ethnicity: "Black", description: "Hades- God of the Underworld, loves their wife. NonWhite. He/They, Theseis- Knows the Labyrinth and Dionysus. Black. He/Him, Hermes: God of speed, likes shoes. Snobby. NonWhite. He/They", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Chorus 4 (Atlas, Icarus, Brother, Zeus)", age: "Open", gender: "Open", ethnicity: "White", description: "Atlas- He’s got the whole world in his hands. White. He/Him, Icarus- White. He/Him. Rapper. Eskeet., Zeus- Corny white dad. Proud. White. He/They", skills: "", notes: nil)