#Auditions
# audition_address = Address.create!(address1: "", address2: nil, address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60201")
# callback_address = Address.create!(address1: "", address2: "", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60640")
# show_address = Address.create!(address1: "", address2: nil, address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60201")
# audition = Audition.create!(name_of_company: "",  union_status: "Non-Equity", pay_scale: "", name_of_show: "", written_by: "", director: nil, musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-04-29", tech_startdate: nil, previews_startdate: nil, show_startdate: "2024-06-23", show_enddate: "2024-07-28", show_address_id: nil, show_warnings: "", show_description: "", additional_notes: nil, audition_address_id: , audition_date1: "2024-08-20", audition_time1: nil, audition_date2: "2024-08-21", audition_time2: "", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_address_id: , callback_date1: "", callback_time1: "", callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "", how_to_submit: "")

# Character.create!(audition_id: audition.id, name: "", age: "", gender: "", ethnicity: "Any/Open", description: "", skills: "", notes: nil)


audition_address = Address.create!(address1: "Women and Children First Bookshop", address2: "5322 N. Clark St.", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60640")
callback_address = Address.create!(address1: "Women and Children First Bookshop", address2: "5322 N. Clark St.", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60640")
show_address = Address.create!(address1: "", address2: nil, address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60201")
audition = Audition.create!(name_of_company: "Sandbox Theatre Collective",  union_status: "Non-Equity", pay_scale: "Stipend Not Listed", name_of_show: "On A Grey Thread", written_by: "Shualee Cook", director: "Hayley Procacci", musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-07-01", tech_startdate: nil, previews_startdate: nil, show_startdate: "", show_enddate: "", show_address_id: nil, show_warnings: "", show_description: "Sandbox Theatre Collective is seeking queer actors for a World Premiere musical workshop, written by Shualee Cook and directed by Hayley Procacci. The piece is based on Elsa Gidlow's 1923 poetry collection, On a Grey Thread - one of the first books published in the U.S to contain openly sapphic verse. Sandbox Theatre Collective is looking for actors from diverse backgrounds with a wide variety of singing styles. Ability to play musical instruments is encouraged but not required. Actors should be comfortable playing both themselves and historical characters. Initial concept rehearsals will take place on 4 to 6 Sunday evenings in July and August of 2024, located in Andersonville. There will be a 6-8 week traditional rehearsal process following concept rehearsals slated for Winter/Spring 2024/25, culminating in a Spring 2025 production.", additional_notes: nil, audition_address_id: audition_address.id, audition_date1: "2024-05-03", audition_time1: "7:00PM-10:00PM", audition_date2: "", audition_time2: "", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_address_id: callback_address.id , callback_date1: "2024-05-05", callback_time1: "7:00PM-10:00PM", callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "Please prepare 32 bar vocal selection of your choice and 1-2 minutes of choice material with your instrument (optional). You will additionally be asked to cold read selected poetry from Gidlow's On a Grey Thread.The audition will begin with a 30-minute group devising workshop. Following the workshop, all actors invited to attend audition will be given 10-minute audition slots. All artists should make arrangements to stay for the entirety of the audition (7-10PM).", how_to_submit: "Please fill out this form: forms.gle/mTNQVtfCock8uXm66")

Character.create!(audition_id: audition.id, name: "Open Call", age: "Any/Open", gender: "Any/Open", ethnicity: "Any/Open", description: "Sandbox Theatre Collective is seeking queer actors for a World Premiere musical workshop", skills: "Singing. Especially interested in instrumentalist", notes: nil)


audition = Audition.create!(name_of_company: "Nothing Without A Company",  union_status: "Non-Equity", pay_scale: "$450 stipend (understudy) - $900 stipend (band member)", name_of_show: "Sofa King Queer", written_by: "", director: nil, musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-07-15", tech_startdate: "2024-10-07", previews_startdate: nil, show_startdate: "2024-10-18", show_enddate: "2024-11-24", show_address_id: nil, show_warnings: "", show_description: "A world premiere pop-punk musical", additional_notes: nil, audition_address_id: , audition_date1: "2024-05-10", audition_time1: nil, audition_date2: "", audition_time2: "", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_address_id: , callback_date1: "", callback_time1: "", callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "Email for materials to prepare. You will be asked to submit a scene and song from Sofa King Queer.", how_to_submit: "email casting@nothingwithoutacompany.org with your headshot (photo) and resume with Subject: SKQ NAO Understudy Submission OR a video of you playing your instrument and any conflicts from July – December with Subject: SKQ Band Submission (instrument you play)")

Character.create!(audition_id: audition.id, name: "Nao", age: "22", gender: "Non-Binary", ethnicity: "Asian-American", description: "UNDERSTUDY - Sil’s partner, west-coast raised", skills: "Singing", notes: nil)
Character.create!(audition_id: audition.id, name: "Band Member", age: "Any/Open", gender: "Any/Open", ethnicity: "Any/Open", description: "Instrumentalist who can play in a pop-punk style", skills: "Seeking 2 band members who can play guitar, base or drums proficiently.", notes: nil)


audition = Audition.create!(name_of_company: "Pocket Theatre VR",  union_status: "Non-Equity", pay_scale: "$150 Stipend", name_of_show: "A Queer Indonesian Love Story", written_by: "Dena Igusti", director: "Karina Patel", musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-06-08", tech_startdate: nil, previews_startdate: nil, show_startdate: "2024-06-15", show_enddate: "2024-06-16", show_address_id: nil, show_warnings: "", show_description: "1997 Jakarta, Indonesia. Sari is an aspiring singer hoping to achieve her dreams of stardom through her karaoke performances at her best friend Fina’s parties. One of her song numbers leads to a chance encounter with Lisa, a determined journalist, and the two become a hot item in Jakarta’s lesbian party scene. But when Sari is forced to flee from the after effects of Suharto’s dictatorship, the two must adapt their love to conform to the pressures of survival and migration. Eighteen years later, Sari’s daughter Diah must navigate the residual trauma of Sari’s past as it is projected onto her own relationship with her girlfriend, Melli.", additional_notes: nil, audition_address_id: , audition_date1: "2024-05-15", audition_time1: nil, audition_date2: "", audition_time2: "", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_address_id: , callback_date1: "", callback_time1: "", callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "Please submit a self taped monologue. If auditioning for Sari or Older Sari a singing sample is necessary.", how_to_submit: "Fill out the form here: https://docs.google.com/forms/d/e/1FAIpQLScyvinsjHBGYOktZA3LTPMwmoj1FsIDqe0VV0rrYPL0yfoqVg/viewform")

Character.create!(audition_id: audition.id, name: "Sari", age: "18-25", gender: "Female or Non-Binary", ethnicity: "Indonesian/Southeast Asian", description: "A vivacious and elegant singer. Loud and cocky but knows how to light up a room. Has dreams of becoming a singer, hence why she takes any opportunity to be in front of a mic and a back track. Sticks to her roots even if her friends think it’s uncool. Is in love with Lisa and doesn’t care who’s watching. Despite this, she feels the pressure to start a nuclear family due to the traumas of late 90s Indonesia. Born and raised in Makassar but spent her teens and young adulthood in Jakarta.", skills: "Must speak/pronounce Indonesian. Must be able to learn and sing an Indonesian song.", notes: nil)
Character.create!(audition_id: audition.id, name: "Older Sari", age: "40-55", gender: "Female or Non-Binary", ethnicity: "Indonesian", description: "Bold and sarcastic, but at times forced to make herself small to cater to the community around her. While not completely jaded by the events that have transpired in her life, constantly wonders if she's made the right choices for herself and loved ones, especially in regards to giving up her dreams, marrying a man, and starting a family. Very protective of her daughter, Diah, but tends to project her life experiences onto her. Vivacious and elegant.", skills: "Must speak/pronounce Indonesian. Must be able to learn and sing an Indonesian song.", notes: nil)
Character.create!(audition_id: audition.id, name: "Lisa", age: "18-25", gender: "Female or Non-Binary", ethnicity: "Indonesian", description: "A shy but far from timid young woman. A little bit of a bookworm but isn't afraid to be sarcastic. Has a smart mouth but she knows how to be charming. Is fully in love with Sari but knows their love can only be a dream in their lifetime. Determined to be connected to her no matter what. Loves physical touch. Wears circle glasses and striped shirts and shorts cause she wants to be "cool" like all the celebs on TV, only she's way cooler. Born and raised in Jakarta.", skills: "Must speak/pronounce Indonesian.", notes: nil)
Character.create!(audition_id: audition.id, name: "Fina", age: "18-25", gender: "Female or Non-Binary", ethnicity: "Indonesian", description: "Sari’s best friend and Lisa’s colleague. She hosts private parties for queer Indonesians and usually knows who’s who in the Jakarta lesbian scene. She is sarcastic and deadpan but fiercely loyal to her friends, even if her friends don’t see it that way all the time. Knows how to read other people’s emotions. Cool and chic.", skills: "Ability to speak/pronounce Indonesian is a plus, but not required.", notes: nil)
Character.create!(audition_id: audition.id, name: "Diah", age: "18-25", gender: "Female or Non-Binary", ethnicity: "Indonesian", description: "Sari’s daughter. Loves her mother deeply, and while she doesn’t know her mother’s past, she always feels like she can relate to her somehow. Tells her mother everything, but is very private about what goes on in her dating life because she gets easily embarrassed. Despite her embarrassment, she loves Melli dearly and isn’t afraid to show it, just not in front of her mom.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Melli", age: "18-25", gender: "Female or Non-Binary", ethnicity: "Any Non-White Ethnicity", description: "Diah's longtime girlfriend. Grew up in Queens, knew Diah since high school but her family wasn't close with Diah's until they started dating. Loves Diah to death and can't imagine having as much fun with anyone else, but can’t stand the ways Diah is always watched. Loves crafting, stationery, and food at the mall.", skills: "", notes: nil)


callback_address = Address.create!(address1: "Roll Cut Studios", address2: "320 N Damen Ave", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60612")
show_address = Address.create!(address1: "The Den Theatre", address2: "1331 N Milwaukee", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60622")
audition = Audition.create!(name_of_company: "Lex The Movie in association with Red Theater",  union_status: "Non-Equity", pay_scale: "Principals- $550, Understudies- $125. Understudies will be paid an additional $25/show that they go on, excluding the 2 guaranteed performances.", name_of_show: "Within A Shadow", written_by: "", director: nil, musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-08-01", tech_startdate: "2024-08-24", previews_startdate: "2024-09-04", show_startdate: "2024-09-05", show_enddate: "2024-10-13", show_address_id: show_address.id, show_warnings: "", show_description: "A funny, introspective play about a young college senior (Lex) trying to land her dream architecture job and (finally!) her first boyfriend before she graduates from her prestigious, predominantly white university. But being a Black student on campus, Lex’s pursuit of love and fulfillment is challenged as rising racial tensions force her to deal with a crisis of self-worth and cultural identity.", additional_notes: nil, audition_address_id: , audition_date1: "2024-04-30", audition_time1: nil, audition_date2: "", audition_time2: "", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_address_id: callback_address.id, callback_date1: "2024-05-10", callback_time1: "6:30PM-10:30PM", callback_date2: "2024-05-11", callback_time2: "2:30PM-9:30PM", callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "After requesting an audition, you will be asked to submit a self-tape consisting of reading sides from the script", how_to_submit: "Please email your headshot and resume with subject line “Within a Shadow Request” to Becca Holloway at casting.withinashadow@gmail.com")

Character.create!(audition_id: audition.id, name: "Lex", age: "22", gender: "Female", ethnicity: "Black", description: "Sensible architecture nerd with a secretive fire in her. She grew up in predominantly white, wealthy areas her whole life. Awkward. Cute. Simple. (ROLE HAS BEEN CAST; SEEKING UNDERSTUDY)", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Rasheeda", age: "21", gender: "Female", ethnicity: "Black", description: "The outrageously hilarious, proud, and intelligent girl that everyone wants to be friends with. Lex’s roommate and tether to the Black community. Urban. Bodacious. Absolutely Fabulous.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Cece", age: "22", gender: "Female", ethnicity: "White", description: "The almost flawless blonde hair, blue eyed Cosmopolitan cover model. Lex’s best friend. She grew up in low income areas her whole life, and she will never let anyone know it. Fun. Feisty. Sharp.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Aiden", age: "22", gender: "Male", ethnicity: "White", description: "The genuine, charmer who makes you feel like you're the only person in the world. Old ladies love him, and young ladies are intrigued by him. Dashing. Non-threatening. Influenceable.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Jeremiah", age: "22", gender: "Male", ethnicity: "Black", description: "The swagger-filled good boy with a killer smile. He is a journalist at heart, but a football player by necessity. Confident. Keen. Smooth.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Jasmine", age: "21", gender: "Female", ethnicity: "Black", description: "The social media connoisseur for Black Nationalism. Lex’s ex-best friend. She is determined to find her place within the Black community, and she’s willing to change herself to do it. Sharp. Proud. Outspoken.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Isaac", age: "21", gender: "Male", ethnicity: "White", description: "A tech-savvy party friend. He is in college to have a good time. Sassy. Tech Savvy. Outlandish.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Henry", age: "23", gender: "Male", ethnicity: "White", description: "The typical rich Northeastern douche bag with Sperrys. He is Cece’s boyfriend. Douche. Dick. Entitled.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Professor Wright", age: "50s-60s", gender: "Female", ethnicity: "Black", description: "The mentor who is more like a big sister than a professor. Warm. Honest. Blunt.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Professor Cronke", age: "60s-70s", gender: "Female", ethnicity: "White", description: "Overly exhausted, grouchy Babushka. She is still teaching classes about relationships. She just wants to retire. Grumpy. A Little Kinky. Babushka.", skills: "", notes: nil)


audition_address = Address.create!(address1: "Metropolis PAC", address2: "111 W. Campbell St.", address3: nil, city: "Arlington Heights", state: "IL", country: "US", postal_code: "60005")
callback_address = Address.create!(address1: "Metropolis PAC", address2: "111 W. Campbell St.", address3: nil, city: "Arlington Heights", state: "IL", country: "US", postal_code: "60005")
show_address = Address.create!(address1: "Metropolis PAC", address2: "111 W. Campbell St.", address3: nil, city: "Arlington Heights", state: "IL", country: "US", postal_code: "60005")
audition = Audition.create!(name_of_company: "Metropolis Performing Arts Centre",  union_status: "Non-Equity", pay_scale: "Principal Roles: $700 Rehearsal Flat rate + $70 per show performed. Ensemble Roles: $700 Rehearsal Flat rate + $60 per show performed. Internal Understudy Assignments: Additional $100 Rehearsal Flat rate. Swings: $700 Rehearsal Flat rate + $60 per show performed. 20 shows total. Travel stipend applications available.", name_of_show: "Rodgers & Hammerstein’s Cinderella", written_by: "music by Richard Rodgers, lyrics/original book by Oscar Hammerstein II, and new book by Douglas Carter Beane", director: "Johanna Miller", musical_director: "Aaron Kaplan and assistant music director, Kevin Zhou", choreographer: "Mandy Modic", rehearsal_startdate: "2024-08-20", tech_startdate: "2024-09-14", previews_startdate: "", show_startdate: "2024-09-26", show_enddate: "2024-10-20", show_address_id: show_address.id, show_warnings: "", show_description: "Rodgers & Hammerstein’s Cinderella is the new Broadway adaptation of the classic musical. This contemporary take on the classic tale features Rodgers & Hammerstein’s most beloved songs, including “In My Own Little Corner,” “Impossible/It’s Possible” and “Ten Minutes Ago,” alongside an up-to-date, hilarious, and romantic libretto by Tony Award nominee Douglas Carter Beane. (Concord Theatricals)", additional_notes: nil, audition_address_id: audition_address.id, audition_date1: "2024-05-13", audition_time1: "4:30PM-10:30PM", audition_date2: "2024-05-16", audition_time2: "4:30PM-10:30PM", audition_date3: "2024-05-17", audition_time3: "12:00PM-4:00PM", audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_address_id: callback_address.id , callback_date1: "2024-05-19", callback_time1: "9:00AM-5:00PM", callback_date2: "2024-05-21", callback_time2: "7:00PM-10:30PM", callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "One 32-bar or 1 minute cut of a musical theater song in the style of the show. Also prepare one short monologue in the style of the show. Entire audition not to exceed 3 minutes. Please bring a copy of your headshot/resume to your audition. Please bring sheet music in a 3 ring binder. An accompanist will be provided.", how_to_submit: "Use this link to sign up for a slot: https://calendly.com/metropolis-casting/cinderella?month=2024-05 THEN submit an email to casting@metropolisarts.com with Cinderella in the subject line. Include the following: Headshot & resume, Any conflicts with the production schedule (no tech conflicts allowed), If you have a dance reel or a clip of you dancing, we would love to see it. Anything you have that shows technique and/or style is wonderful, but also specifically looking for classic musical theater and partnering if you have it. Links to your work are welcome but not required. Please send info prior to your audition day.")

Character.create!(audition_id: audition.id, name: "Ella", age: "", gender: "", ethnicity: "Any/Open", description: "Though no one notices her beneath her rags and quiet demeanor, she is opinionated, charismatic, passionate, beautiful, and funny. Idealistic and hopeful, she courageously challenges the prince to change the policies in his kingdom – and helps him discover who he truly is. Always her late father’s daughter, she is determined to see the good in everyone despite her hardships and suffering. We see her blossom into a confident woman.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Topher", age: "", gender: "", ethnicity: "Any/Open", description: "A misguided and lost prince who longs to do something important with his life. Though brave and heroic, he feels lonely and unfulfilled. Charming but NOT a stereotypical ladies man, he is thoughtful, appealing, and innocent – with an unforced goofy streak. Moral, genuine, and kindhearted, he is at a crossroads and must take control of his kingdom and his future.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Madame", age: "", gender: "", ethnicity: "Any/Open", description: "Ella’s selfish stepmother. The epitome of vanity and fashion. A ravenous social climber who values wealth, status, and material possessions above all else. Unapologetically dismissive and sometimes cruel, Madame schemes her way up the social ladder.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Sebastian", age: "", gender: "", ethnicity: "Any/Open", description: "The kingdom’s Lord Chancellor. Though he is Topher’s trusted advisor, he is devious and selfish. Using propaganda and dishonesty, he keeps Topher isolated and in the dark about his kingdom. Sebastian rules without regard for the lower class, or anyone other than himself – and truly believes he deserves to rule the kingdom.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Marie", age: "", gender: "", ethnicity: "Any/Open", description: "A friend to Ella and the town’s resident crazy lady and beggar woman, Marie is actually a fairy godmother in disguise. Wise, warm, otherworldly, and charming, Marie rewards Ella for her kindness by making her dreams a possibility.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Gabrielle", age: "", gender: "", ethnicity: "Any/Open", description: "Ella’s stepsister and daughter of Madame. Encouraged by her mother and sister to value material wealth and social status, she unenthusiastically joins them in their abrasive behavior. Quietly passionate, empathetic, and witty, she is drawn to Ella and Jean-Michel. Ironically aware that she doesn’t fit in.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Charlotte", age: "", gender: "", ethnicity: "Any/Open", description: "Ella’s stepsister and daughter of Madame. Brash, self-centered, materialistic, snooty, loud, sassy, and bratty, she has a ridiculously high, but unfounded, opinion of herself. She never passes up an opportunity to be the center of attention.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Jean-Michel", age: "", gender: "", ethnicity: "Any/Open", description: "A feisty, passionate peasant determined to make a change for the starving class. Impetuous. A firebrand but lacks authority and isn’t taken seriously as a revolutionary. Has a crush on Gabrielle, though their courtship is forbidden because they are from different social classes.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Lord Pinkleton", age: "", gender: "", ethnicity: "Any/Open", description: "The Lord Chancellor’s right-hand man. Announces royal balls, banquets, and even the weather to the villagers.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Ensemble", age: "", gender: "", ethnicity: "Any/Open", description: "Giant, Fox (Puppet), Raccoon (Puppet), Footman, Coachman, Knights, Peasants, Serfs, Townspeople, Ladies and Gentlemen of the Court, Servants, etc.", skills: "", notes: nil)


show_address = Address.create!(address1: "The Edge Theater", address2: "5451 N Broadway", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60640")
audition = Audition.create!(name_of_company: "Black Button Eyes Productions",  union_status: "Non-Equity", pay_scale: "Stipend. $955 main cast, $500 understudies", name_of_show: "A Shadow Bright and Burning", written_by: "Adapted by Ed Rutherford", director: "Ed Rutherford", musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-07-14", tech_startdate: "2024-08-19", previews_startdate: nil, show_startdate: "2024-08-24", show_enddate: "2024-09-28", show_address_id: show_address.id, show_warnings: "", show_description: "This is an alternate universe version of Victorian England where magic is real, and the realm has been invaded by Lovecraftian horrors from another dimension. The protagonist is Henrietta Howell, who discovers that with her unique magical powers, she may be the ‘chosen one’ destined to save England.", additional_notes: nil, audition_address_id: , audition_date1: "", audition_time1: nil, audition_date2: "", audition_time2: "", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_address_id: , callback_date1: "", callback_time1: "", callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "If invited to audition, candidates will be sent short side(s) from the script to prepare via video.", how_to_submit: "Please email photo and resume, if there are any specific role(s) for which you'd like to be considered, and whether or not you're interested in understudying to blackbuttoneyesproductions@gmail.com")

Character.create!(audition_id: audition.id, name: "Henrietta", age: "", gender: "", ethnicity: "Any/Open", description: "Henrietta Howel is the female protagonist who confides in the audience throughout the piece. Strong-willed orphan from an immigrant family, and possesses magical powers that she’s uncertain how to control, with fire being a particular specialty. Possibly the Chosen One of a prophecy. Mistaken for a female Sorcerer, but we learn later that she is actually a Magician.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Agrippa", age: "", gender: "", ethnicity: "Any/Open", description: "Cornelius Agrippa is a prominent member of the order of sorcerers, and teacher to several students of sorcery. Paternal and warm, but with dark secrets.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Rook", age: "", gender: "", ethnicity: "Any/Open", description: "A stablehand who has known Henrietta since they were both children; possible romantic interest. Unclean and scarred from the touch of the monster Korozoth, the Shadow and Fog.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Blackwood", age: "", gender: "", ethnicity: "Any/Open", description: "Cold, patrician and standoffish - One of Cornelius Agrippa’s other four students, all young men of privilege. ", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Magnus", age: "", gender: "", ethnicity: "Any/Open", description: "Flamboyant and fun - One of Cornelius Agrippa’s other four students, all young men of privilege.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Cellini", age: "", gender: "", ethnicity: "Any/Open", description: "Visiting from Italy to pursue his studies. Genial but conservative. One of Cornelius Agrippa’s other four students, all young men of privilege.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Colegrind/Palehook", age: "", gender: "", ethnicity: "Any/Open", description: "COLEGRIND- A sinister, nasty old man who runs the Brimthorn School for Girls. PALEHOOK- Another sinister, nasty old man who is the head of the order of sorcerers in London.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "R'hlem", age: "", gender: "", ethnicity: "Any/Open", description: "The leader of the Seven Ancients. Also known as the Skinless Man. Will be doubled from elsewhere in the cast TBD.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Ensemble", age: "", gender: "", ethnicity: "Any/Open", description: "assorted GUARDS, TOWNSPEOPLE, KOKEN (manipulating magic effects) and COURTIERS either played by additional actors, or the above actors when not playing their main tracks.", skills: "", notes: nil)


audition_address = Address.create!(address1: "Cornservatory", address2: "4210 N Lincoln Ave", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60618")
callback_address = Address.create!(address1: "Cornservatory", address2: "4210 N Lincoln Ave", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60618")
show_address = Address.create!(address1: "Cornservatory", address2: "4210 N Lincoln Ave", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60618")
audition = Audition.create!(name_of_company: "Cornservatory",  union_status: "Non-Equity", pay_scale: "$100 Stipend", name_of_show: "Schools Out! A Summer Sketch Show for Young Audiences", written_by: "", director: "Brittany Sue Hines", musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-05-01", tech_startdate: "2024-06-02", previews_startdate: nil, show_startdate: "2024-06-08", show_enddate: "2024-06-30", show_address_id: show_address.id, show_warnings: "", show_description: "The show, Schools Out! A Summer Sketch Show for Young Audiences will be a sketch show tailored to young ones age 5-12 and feature a cast of adult performers. The show will be a goofy romp about all things summer vacation directed by Brittany Sue Hines.", additional_notes: nil, audition_address_id: audition_address.id , audition_date1: "2024-04-28", audition_time1: "12:00PM - 3:00PM", audition_date2: , audition_time2: "", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_address_id: callback_address.id, callback_date1: "2024-04-30", callback_time1: "7:00PM", callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "a short 60 second TYA monologue/ story/ or poem of your choice. We will be looking for heightened characters and physicality", how_to_submit: "email CornProdAuditions@gmail.com with your headshot and resume to request a 5 minute time slot. You may request to submit a video audition if you are unavailable on the audition day.")

Character.create!(audition_id: audition.id, name: "Ensemble", age: "Any/Open", gender: "Any/Open", ethnicity: "Any/Open", description: "", skills: "Looking for heightened characters and physicality", notes: nil)


callback_address = Address.create!(address1: "636 Ridge Rd", address2: "", address3: nil, city: "Highland Park", state: "IL", country: "US", postal_code: "60035")
show_address = Address.create!(address1: "McGrath Family Performaning Arts Center", address2: "1100 Laramie Ave", address3: nil, city: "Wilmette", state: "IL", country: "US", postal_code: "60091")
audition = Audition.create!(name_of_company: "Highland Park Players",  union_status: "Non-Equity", pay_scale: "Stipends are available for select roles", name_of_show: "The Prom", written_by: "", director: nil, musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-06-11", tech_startdate: "2024-08-11", previews_startdate: nil, show_startdate: "2024-08-16", show_enddate: "2024-08-25", show_address_id: show_address.id, show_warnings: "", show_description: "", additional_notes: nil, audition_address_id: , audition_date1: "2024-05-13", audition_time1: nil, audition_date2: "", audition_time2: "", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_address_id: callback_address.id , callback_date1: "2024-06-03", callback_time1: "", callback_date2: "2024-06-04", callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "Prepare 32 bars in the style of the show that demonstrates your range and vocal ability. Singing from the show is permitted, but not encouraged. No A cappella - please sing with a piano or backing track", how_to_submit: "https://www.theaterforms.com/audition/notice/HPP/Prom/")

Character.create!(audition_id: audition.id, name: "Emma Nolan", age: "late teen/young adult", gender: "", ethnicity: "Any/Open", description: "Student, shy, in love with Alyssa, warm-hearted, quiet, reluctant, smart, kind, intelligent, strong actor/singer.", skills: "Ability to play guitar an asset but not required. Vocal Range: F3 - E5", notes: nil)
Character.create!(audition_id: audition.id, name: "Dee Dee Allen", age: "mature adult", gender: "", ethnicity: "Any/Open", description: "Diva, narcissistic, egotistical Broadway star, comical, self-involved, domineering, big stage presence, strong actor/singer.", skills: "Vocal Range: E3 - E5", notes: nil)
Character.create!(audition_id: audition.id, name: "Barry Glickman", age: "adult/mature adult", gender: "", ethnicity: "Any/Open", description: "Campy, over-the-top, politically incorrect, flamboyant Broadway star, self- involved, impulsive, kind-hearted, strong singer.", skills: "Vocal range: Bb3 - F#4 (Ab5, if possible)", notes: nil)
Character.create!(audition_id: audition.id, name: "Alyssa Greene", age: "late teen/young adult", gender: "", ethnicity: "Any/Open", description: "Top student, cheerleader, closeted girlfriend, in love with Emma, fearful, strong actor/singer/mover.", skills: "Vocal Range: Ab4 - Eb5", notes: nil)
Character.create!(audition_id: audition.id, name: "Mr. Hawkins", age: "adult/mature adult", gender: "", ethnicity: "Any/Open", description: "high school principal, concerned, star-struck fan of Dee Dee’s, kind, honest, ally to Emma, reprimanding.", skills: "Vocal range: G2 - F4", notes: nil)
Character.create!(audition_id: audition.id, name: "Angie Dickinson", age: "adult/mature adult", gender: "", ethnicity: "Any/Open", description: "actress, dancer, frustrated Broadway veteran, heart of gold, experienced, kind-hearted, flamboyant, jaded “Fosse” girl, strong actor/singer/dancer.", skills: "Vocal Range: Ab4 - E5", notes: nil)
Character.create!(audition_id: audition.id, name: "Mrs. Green", age: "adult", gender: "", ethnicity: "Any/Open", description: "Alyssa’s mother, strict, controlling, intimidating, traditional, straight-laced, school PTA President, conservative, shocked, tough, strong actor.", skills: "Vocal Range: A4 - C5", notes: nil)
Character.create!(audition_id: audition.id, name: "Trent Oliver", age: "adult", gender: "", ethnicity: "Any/Open", description: "pretentious Juilliard graduate, struggling Broadway actor, pompous, enthusiastic, funny, strong actor/singer/mover.", skills: "Vocal range: C3 - Ab5", notes: nil)
Character.create!(audition_id: audition.id, name: "Sheldon Saperstein", age: "adult/mature adult", gender: "", ethnicity: "Any/Open", description: "Broadway publicist, straight-talking, hard-working, charismatic agent.", skills: "Open vocal range", notes: nil)
Character.create!(audition_id: audition.id, name: "Shelby, Kaylee, Nick, Kevin", age: "teen/young adult", gender: "", ethnicity: "Any/Open", description: "students who bully Emma (but eventually learn to accept her), the popular kids (cheerleaders and jocks), strong singers/dancers", skills: "Shelby Solo Vocal range: Ab4 - Bb5, Kayley Solo Vocal range: Ab4 - C5, Nick Solo Vocal range: C3 - F4, and Kevin Solo Vocal range: D3 - G4", notes: nil)
Character.create!(audition_id: audition.id, name: "Students", age: "late teen/young adults", gender: "", ethnicity: "Any/Open", description: "all genders, prejudiced, mean, bullying, small town, bigoted (but have a change of heart), excitable, strong singers/movers, ensemble", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Parents", age: "adults/mature adults", gender: "", ethnicity: "Any/Open", description: "bigoted, homophobic, small town, prejudiced, worried, afraid, strong singers/movers, ensemble", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Ensemble", age: "Any/Open", gender: "", ethnicity: "Any/Open", description: "Olivia Keating, Opening Night Party attendees, reporters, students, PTA members, motel clerk, cast of the non-Equity tour of Godspell, Monster Truck rally attendees, Mrs. Greene’s friend, LGBT students", skills: "Soprano: C4 - G5, Alto: Ab4 - G5, Tenor: C3 - Ab5, and Bass: C3 - G4", notes: nil)


audition_address = Address.create!(address1: "Chicago Shakepeare Theatre", address2: "800 E Grand Ave.", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60611")
callback_address = Address.create!(address1: "Chicago Shakepeare Theatre", address2: "800 E Grand Ave.", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60611")
show_address = Address.create!(address1: "Chicago Shakepeare Theatre", address2: "800 E Grand Ave.", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60611")
audition = Audition.create!(name_of_company: "Chicago Shakespeare Theatre",  union_status: "Equity", pay_scale: "AEA: $1057.75/wk; NON-AEA: $725.00/wk", name_of_show: "The Lord of The Rings: A Musical Tale", written_by: "Book and Lyrics by Shaun McKenna and Matthew Warchus, Music by A.R. Rahman Värttinä and Christopher Nightingale", director: "Paul Hart", musical_director: "Mark A Spinall", choreographer: "Anjali Mehra", rehearsal_startdate: "2024-06-03", tech_startdate: nil, previews_startdate: "2024-07-19", show_startdate: "2024-07-26", show_enddate: "2024-09-01", show_address_id: show_address.id, show_warnings: "", show_description: "Seeking actors 18-60 who sing and play acoustic instruments at an advanced or high intermediate level. Seeking all ages, races, ethnicities and gender. Only seeking actors with Chicago housing  at this time.", additional_notes: nil, audition_address_id: audition_address.id , audition_date1: "", audition_time1: nil, audition_date2: "", audition_time2: "", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_address_id: callback_address.id , callback_date1: "", callback_time1: "", callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "Send headshot and resume as one PDF, as well as examples of your instrument playing. Very insterested in: Accordion, Trumpet, French Horn, Trombone, Violin, Fiddle, Viola, Cello, Double bass and bass guitar, Drums, Flute and piccolo, Irish whistle, Acoustic guitar. Prepare musical theater or folk song that shows range", how_to_submit: "https://forms.gle/9ANhf8YiGp6XKXqg8")

Character.create!(audition_id: audition.id, name: "Frodo Baggins", age: "20-35", gender: "Male", ethnicity: "Any/Open", description: "Frodo is an earnest, inquisitive young Hobbit with the otherworldly quality of someone wise beyond his years. Frodo longs for adventure beyond the boundaries of The Shire, but soon finds himself faced with a quest that will test not only his bravery but his very sense of self, as he is wracked by the powers of the One Ring.", skills: "Actors must be highly experienced with movement and choreography. Music: something simple and unaffected eg 'I'd Rather Be Sailing', 'Johanna' Tenor or high baritone. Honest, simple tone. More folky than MT. High note: A4", notes: nil)
Character.create!(audition_id: audition.id, name: "Samwise Gamgee", age: "20-35", gender: "Male", ethnicity: "Any/Open", description: "Sam is a warm, friendly, and stubbornly loyal Hobbit, and a gardener for the Baggins family. He is fiercely protective of those he loves and quietly courageous in his determination to see Frodo to the end of his perilous journey - even as he longs to return to his sweetheart and his quiet life in The Shire.", skills: "SAM must play guitar (it's strumming only) Music: something simple and unaffected eg 'I'd Rather Be Sailing', 'Johanna' Tenor or high baritone. Honest, direct, unaffected tone. More folky than MT.", notes: nil)
Character.create!(audition_id: audition.id, name: "Gollum", age: "25-45", gender: "Any/Open", ethnicity: "Any/Open", description: "The creature known as Gollum was once a Hobbit before he was twisted and driven mad by the One Ring over hundreds of years. Gollum’s one desire is to be reunited with the Ring at any cost. He is manipulative, cunning and deeply conflicted, while still able to tug on the heartstrings of those he encounters.", skills: "Actors must be highly experienced with movement and choreography, and be skilled in at least one instrument. Music: Baritone, and with a really characterful voice. It requires an extremely agile vocalist who can get creative around producing interesting sounds and vocal qualities for Gollum, and rapidly switching in and out of this for his song. Low note: C3; High note: F4; Falsetto to high C.", notes: nil)
Character.create!(audition_id: audition.id, name: "Strider/Aragorn", age: "30-40", gender: "Male", ethnicity: "Any/Open", description: "Strider is the name given to the mysterious Ranger who traverses Middle Earth, protecting its people from rising evil. His true identity is Aragorn – the heir to the throne of Men. He is a quick-thinking and just leader, whose bravery and devotion to his people inspires all he encounters. Despite his claim to the throne, Aragorn initially doubts his ability to lead and fears failing those he is responsible for.", skills: "Actors must be skilled in at least one instrument, and experiences in movement and choreography. Music: Musical Theater or folk song with drive that shows range (i.e. “Streets of Dublin”) Robust, manly baritone/high baritone. Not operatic. High note: G4", notes: nil)
Character.create!(audition_id: audition.id, name: "Boromir", age: "30-40", gender: "Male", ethnicity: "Any/Open", description: "Boromir is a valiant and hot-headed warrior, the son of the Steward of Gondor. He is headstrong, determined to a fault and tirelessly loyal to his people.", skills: "Actors should be highly skilled in at least one instrument, and skilled in movement and choreography. Experience with puppetry is desirable but not essential. Music: Musical Theater or folk song with drive that shows range.", notes: nil)
Character.create!(audition_id: audition.id, name: "Gimli", age: "25-40", gender: "Male", ethnicity: "Any/Open", description: "Gimli is a steadfast and fearless Dwarf, one of the last of the House of Durin, determined to prevent the decline of his people by destroying the Ring. He is deeply distrustful of Elves and is easily provoked into arguments with Elven prince Legolas, but Gimli’s softer side is brought out by the excitable young Hobbits and the beauty of Galadriel of Lothlorien.", skills: "GIMLI could play guitar (picking and strumming). MUSIC: Bass. Manly and noble. Low note: B2 ; High note: E4 If contemporary sound, he would play guitar; if operatic sound, he would not.", notes: nil)
Character.create!(audition_id: audition.id, name: "Legolas", age: "20-35", gender: "Male", ethnicity: "Any/Open", description: "Legolas, the Elven prince of Mirkwood, is a quick-witted master archer and a valiant and loyal defender of the members of the Fellowship. He distrusts Dwarves and misses no opportunity to enrage Gimli on their journey to destroy the One Ring but ultimately overcomes his preconceptions in favor of friendship.", skills: "Actors must be highly skilled in at least two instruments and experienced in movement and choreography. Music: Light, easy, but still somewhat manly tone… one befitting of an elf! High bari or tenor. High note: Ab4", notes: nil)
Character.create!(audition_id: audition.id, name: "Merry", age: "20-30", gender: "Any/Open", ethnicity: "Any/Open", description: "Meriadoc Brandybuck is the inquisitive younger cousin of Frodo Baggins. Merry is enthusiastic, kind-hearted and intelligent, and spends most of his time reining in his more impulsive cousin Pippin.", skills: "PIPPIN or MERRY must play fiddle. Actors must be highly skilled in at least one instrument, and skilled in movement and choreography. Experience with puppetry is desirable but not essential. Music: something simple and unaffected eg 'I'd Rather Be Sailing', 'Johanna' Light, young tenor. High note: G4, with a brief A4", notes: nil)
Character.create!(audition_id: audition.id, name: "Pippin", age: "20-30", gender: "Any/Open", ethnicity: "Any/Open", description: "Pippin is a mischievous and fun-loving Hobbit. They are impulsive and an occasional troublemaker, but their heart is in the right place and they remain courageous and fiercely loyal to the Fellowship throughout their journey.", skills: "PIPPIN or MERRY must play fiddle. Actors must be highly skilled in at least one instrument, and skilled in movement and choreography. Experience with puppetry is desirable but not essential. Music: something characterful, i.e., 'Wait a Bit', 'Notice Me Horton' Mezzo. Colourful, characterful, direct voice. High note: E5 (could be adjusted to D5 for the right person)", notes: nil)
Character.create!(audition_id: audition.id, name: "Gandalf", age: "50-70", gender: "Male", ethnicity: "Any/Open", description: "Seeking understudy!! Gandalf is an incredibly powerful Wizard, sent to Middle Earth to aid in the battle against the Dark Lord Sauron. He acts as a guide and protector for the members of The Fellowship of the Ring. Gandalf possesses both tremendous gravitas, as in his clashes with the corrupt Wizard Saruman, and deep warmth, clear in his relationship with the young Hobbits.", skills: "Music: Folk or musical theater ballad of choice. This character does not need to play an instrument though it is helpful.", notes: nil)
Character.create!(audition_id: audition.id, name: "Galadriel", age: "25-35", gender: "Female-identifying", ethnicity: "Any/Open", description: "Galadriel, the Lady of Lothlórien, is one of the mightiest Elves in Middle Earth and over a thousand years old. Though her realm is untouched by the Dark Lord, Galadriel is grieved and resigned to the fact that the One Ring’s destruction will also signal the end of Lothlórien. She is benevolent and graceful, but those in her presence cannot forget her power and omniscience.", skills: "Actors must be skilled in movement and choreography. Experience with puppetry is desirable but not essential. Music: Galadriel should bring something dramatic and fearsome - a modern star turn with a good belt. Excellent vocalist. Conveys wisdom and maturity in her voice. Dramatic belt/mix.Low note: A3; Belt/mix to D5; Soprano extension to G5 belt, Examples: 'Your Daddy's Son' 'With One Look', 'No Good Deed',  'My Heart Will Go On'", notes: nil)
Character.create!(audition_id: audition.id, name: "Saruman/Elrond", age: "35-50", gender: "Male-identifying", ethnicity: "Any/Open", description: "Saruman was once the head of the White Council of Wizards, but – power-hungry and blinded by ambition – he was seduced into serving the Dark Lord, Sauron, and is building an army of Orcs. He is wise, composed and immensely powerful. Elrond is an Elf, the Lord of Rivendell. He is benevolent, intelligent and resigned to the fact that the era of Elves is over and he must move his people overseas.", skills: "Music: a ballad with drive (i.e., “Streets of Dublin”)", notes: nil)
Character.create!(audition_id: audition.id, name: "Arwen", age: "20-35", gender: "Female", ethnicity: "Any/Open", description: "Arwen is the half-Elven daughter of Elrond, Lord of Rivendell. She is wise, courageous and has the grace and gravitas of someone over two thousand years old. Her deep love for Aragorn (a human) leaves her torn between the Elves and the world of Men.", skills: "If ARWEN can play the harp, that is tremendous. If not, we will consider those actors as well if they play another instrument. Actors must be highly skilled in at least one instrument, and skilled in movement and choreography. Experience with puppetry is desirable but not essential. Music: Arwen should bring something folky and unusual such as 'Both Sides Now', 'Hallelujah', or their own cover of something that they might do for an open mic night somewhere smoky. They should then contrast it with something belty but modern, i.e., 'Someone Else's Story'. In general, a lighter sound than Galadriel. For this role, it could be interesting to explore unusual vocal tones. Her sound is otherworldly, heavenly, dreamlike. Belt/mix to D4", notes: nil)
Character.create!(audition_id: audition.id, name: "Rosie Cotton", age: "20-30", gender: "Female", ethnicity: "Any/Open", description: "Rosie Cotton is a Hobbit who stays behind in The Shire during the quest to destroy The Ring. She is warm and funny, while still making sure that her sweetheart, Samwise Gamgee, knows who is in charge.", skills: "Actors must be highly skilled in at least two instruments and skilled in movement and choreography. Experience with puppetry is desirable but not essential. Should sing something fun and characterful.", notes: nil)
Character.create!(audition_id: audition.id, name: "Ensemble", age: "Any/Open", gender: "Any/Open", ethnicity: "Any/Open", description: "Ensemble is made of hobbits telling the story, looking for hobbit’s personality to come through.", skills: "Music: Something that shows character and energy. Seeking all ranges. Ensemble must move well. Actors must be highly skilled in at least one instrument, and skilled in movement and choreography. Experience with puppetry is desirable but not essential.", notes: nil)


audition_address = Address.create!(address1: "", address2: nil, address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60201")
callback_address = Address.create!(address1: "", address2: "", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60640")
show_address = Address.create!(address1: "721 Howard St", address2: nil, address3: nil, city: "Evantson", state: "IL", country: "US", postal_code: "60626")
audition = Audition.create!(name_of_company: "Theo",  union_status: "Non-Equity", pay_scale: "$800 Stipend", name_of_show: "Never Better; a new musical", written_by: "Preston Max Allen", director: "Directed by Landree Fleming", musical_director: "J Alan", choreographer: nil, rehearsal_startdate: "2024-08-05", tech_startdate: "2024-09-03", previews_startdate: nil, show_startdate: "2024-09-15", show_enddate: "2024-10-13", show_address_id: show_address.id, show_warnings: "", show_description: "Theo is thrilled to be producing a developmental production of Never Better; a new musical from 2023 Jonathan Larson Grant finalist Preston Max Allen who also wrote the off-Broadway fan favorite We Are the Tigers. Davy, a jaded college sophomore, has been struggling to keep up with her work and social life as she faces an illness she's written off as a cold. As her symptoms escalate, her Tik Tok influencer roommate April and budding "situationship" Carter encourage her to get help. But Davy's hopes for an easy recovery fade when her doctor urgently requests follow-up testing. Unable to face a potentially devastating diagnosis, Davy ignores her doctor's recommendations and soon starts spiraling in this intimate, folk-punk musical about the value of survival in a world weighed down by grief, loneliness, and fears of an uncertain future. Character Type/Restrictions: Theo is committed to casting our productions in a way that reflects our community and therefore encourages performers of all genders, ages (18+), ethnicities and identities to submit! For gender-fluid and non-binary performers, any genders listed in character descriptions are that of the character only, and you are encouraged to submit for any roles you are interested in! Also, genders listed should not be assumed to be cis. If you have any access needs at any point during the process, please let us know and we will do our best to accommodate.", additional_notes: nil, audition_address_id: , audition_date1: "2024-04-28", audition_time1: nil, audition_date2: "", audition_time2: "", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_address_id: , callback_date1: "2024-05-18", callback_time1: "", callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "Please submit a video with 32 bars (approx. 1 minute) of a contemporary pop/rock song not written for a musical and a monologue for at least one of the characters, which can be found here: tinyurl.com/theoNB", how_to_submit: "email casting@theo-u.org. PLEAE NOTE: - Include your Full Name ONLY as the Subject Line of the email - Put a link to your video in the body of the email (no downloads or passwords, please!) - Attach your headshot/resume as a *single PDF file*, labeled as LastName_FirstName")

Character.create!(audition_id: audition.id, name: "Davy", age: "19", gender: "Female", ethnicity: "Any/Open", description: "Cynical and guarded yet passionate and deeply imaginative, Davy would rather hide behind a dark, pessimistic sense of humor than reveal any vulnerability. Believing she's already prepared herself for an unfulfilling future in a bleak world, Davy's torn between a driven, desperate fight for survival and numb, apathetic surrender when hope actually seems lost.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "April", age: "19", gender: "Female", ethnicity: "Any/Open", description: "", skills: "Davy's roommate and a well-known Tik Tok influencer whose openness about dealing with sexual assault in high school has helped many others find support and community. Her upbeat, confident persona is genuine, but she's struggling with her ability to be a leader while realizing she hasn't completely processed her own experiences.", notes: nil)
Character.create!(audition_id: audition.id, name: "Ainsley", age: "30s", gender: "Female", ethnicity: "Any/Open", description: "A nurse practitioner at the university clinic. Aynsley is warm, attentive, and dedicated to her patients' well-being to the point of spiraling when she doesn't agree with their decisions. After losing her husband three years ago, Aynsley's still working through her grief by hoping to help others heal.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Carter", age: "21", gender: "Male", ethnicity: "Any/Open", description: "A chill, charming stoner and musician whose only goal is to live a low stakes, easygoing life until his connection with Davy inspires him to work towards a more meaningful future.", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Davy's Dad/Misc", age: "30s-40s", gender: "Male", ethnicity: "Any/Open", description: "Covers multiple roles, foremost Davy's semi-estranged but well-intentioned dad.", skills: "Instrumentalist (bass, drums or guitar)", notes: nil)
Character.create!(audition_id: audition.id, name: "Band", age: "Open", gender: "Open", ethnicity: "Any/Open", description: "If you are a singer who also plays any of the following instruments-bass, guitar, drums-and are interested in being considered for the band, please tell us when you submit! If you are *only* interested in being considered for the band, just drop us a note with your resume!", skills: "", notes: nil)


audition_address = Address.create!(address1: "Oil Lamp Theater", address2: "1723 Glenview Road", address3: nil, city: "Glenview", state: "IL", country: "US", postal_code: "60025")
callback_address = Address.create!(address1: "Oil Lamp Theater", address2: "1723 Glenview Road", address3: nil, city: "Glenview", state: "IL", country: "US", postal_code: "60025")
show_address = Address.create! (address1: "Oil Lamp Theater", address2: "1723 Glenview Road", address3: nil, city: "Glenview", state: "IL", country: "US", postal_code: "60025")
audition = Audition.create!(name_of_company: "Oil Lamp Theater",  union_status: "Non-Equity", pay_scale: "$1470 Stipend. This includes a $150 rehearsal stipend and $30 per show performed (44 shows total with extension). Understudy compensation is $630, which includes one guaranteed performance.", name_of_show: "First Date", written_by: "Book by Austin Winsberg, Music and Lyrics by Alan Zachary and Michael Weiner", director: "Christina Ramirez", musical_director: "Kyra Leigh", choreographer: nil, rehearsal_startdate: "2024-07-15", tech_startdate: "2024-08-31", previews_startdate: nil, show_startdate: "2024-09-05", show_enddate: "2024-10-20", show_address_id: show_address.id, show_warnings: "", show_description: "When blind date newbie Aaron is set up with serial-dater Casey, a casual drink at a busy New York restaurant turns into a hilarious high-stakes dinner. As the date unfolds in real time, the couple quickly finds that they are not alone on this unpredictable evening. In a delightful and unexpected twist, Casey and Aaron's inner critics take on a life of their own when other restaurant patrons transform into supportive best friends, manipulative exes and protective parents, who sing and dance them through ice-breakers, appetizers and potential conversational land mines. (Concord Theatricals).", additional_notes: nil, audition_address_id: audition_address.id, audition_date1: "2024-04-28", audition_time1: "6:30PM-10:00PM", audition_date2: "", audition_time2: "", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_address_id: callback_address.id, callback_date1: "2024-05-05", callback_time1: "7:00PM", callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "If you are invited to audition, please prepare 32 bars of a song in the style of the show, not to exceed 60 seconds. Songs from the show are welcome. Please bring your book, as we may ask to hear a second song if time allows.", how_to_submit: "submit your headshot and resume to airtable.com/appY3AOct9EBkLTd5/shrZ4xlBIeOrTtq3x")

Character.create!(audition_id: audition.id, name: "Casey", age: "20s-30s", gender: "Female", ethnicity: "Any/Open", description: "Daring, bold, and delightfully controversial. All as a defense mechanism. Self-admitted serial dater. Has to let down her guard to let Aaron in.", skills: "Contemporary mix/belt to E5", notes: nil)
Character.create!(audition_id: audition.id, name: "Aaron", age: "20s-30s", gender: "Male", ethnicity: "Jewish", description: "New Yorker. Investment banker. He has never been on a blind date before. Out of his element, nervous, and trying way too hard... making all of the classic first date mistakes but is committed to following a real connection with Casey", skills: "Tenor", notes: nil)
Character.create!(audition_id: audition.id, name: "MAN 1 (GABE/ REGGIE/ AARON'S FUTURE SON/ GOOGLE BACK UP/ STONER GUY/ FRIENDLY THERAPIST)", age: "20s-30s", gender: "Male", ethnicity: "Any/Open", description: "The track includes Gabe - 20's/30's Aaaron's extremely confident, expert on all things, best friend. Reggie -20s/30s, Casey's queer BFF. Aaron's Future son - teenager - who raps about being torn between Judaism and Christianity in an over-the-top day dream sequence among other ensemble features throughout.", skills: "Tenor. Seeking a dynamic, comedic actor with excellent pop/rock vocals who can play a wide array of characters throughout the show. Must be comfortable singing a tight harmony within a small ensemble.", notes: nil)
Character.create!(audition_id: audition.id, name: "WOMAN 1 (GRANDMA IDA/ LAUREN / ALLISON/ GOOGLE GIRL/ FEMALE WITH MEGAPHONE/ AARON'S MOTHER)", age: "30s-40s", gender: "Female", ethnicity: "Jewish", description: "The track includes Grandma Ida - Aaron's departed Yiddish-Speaking Grandma, Lauren - Casey's older sister, Allison - Aaron's ex, Google Girl, Aaron's Mother, and other ensemble features throughout the show.", skills: "Mezzo w/ Belt. Seeking a dynamic, comedic actor with excellent vocal ability who can play an array of characters throughout the show. This track sings in a wide variety of vocal styles from contemporary MT to folk to traditional broadway sound. Must be comfortable singing a tight harmony within a small ensemble. Please note multiple characters in this track identify as Jewish.", notes: nil)
Character.create!(audition_id: audition.id, name: "MAN 2 (WAITER/ CASEY'S CHRISTIAN FATHER/ BLAZE / GOOGLE BACK UP/ BRITISH ARTIST)", age: "20s-40s", gender: "Male", ethnicity: "Any/Open", description: "This track includes Waiter - a career waiter, who dabbles with songwriting and performing on the side, a romantic, with a great 11 o'clock number. Casey's Christian Father who is merely a figment of Aaron's imagination - not actually Casey's father.", skills: "Baritone. Seeking a dynamic, comedic actor with excellent pop/rock vocals who can play a wide array of characters throughout the show.  Must be comfortable singing a tight harmony within a small ensemble.", notes: nil)


audition_address = Address.create!(address1: "The Edge Theater", address2: "5451 N. Broadway", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60640")
callback_address = Address.create!(address1: "The Edge Theater", address2: "5451 N. Broadway", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60640")
audition = Audition.create!(name_of_company: "Kerfuffle",  union_status: "Non-Equity", pay_scale: "$500 + $25 Travel Stipend", name_of_show: "Toddler Hiking Club: An Imaginative Nature Walk", written_by: "", director: nil, musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-08-05", tech_startdate: nil, previews_startdate: "2024-08-31", show_startdate: "2024-09-07", show_enddate: "2024-09-29", show_address_id: nil, show_warnings: "", show_description: "Kerfuffle is seeking four adventurous and enthusiastic performers for the world premiere of Toddler Hiking Club: An Imaginative Nature Walk, a promenade, interactive dramatic experience for very young children and their caregivers that takes place in and around nature play spaces and on short walking trails in the Chicago parks. Kerfuffle is seeking an inclusive and diverse company of four performers who are interested in devising non-traditional and adventurous theatre for children. As toddlers and their caregivers follow the Trail Guide on the walk, the ensemble will share performances, poems, music, and other artistic moments along the path.", additional_notes: nil, audition_address_id: audition_address.id , audition_date1: "2024-05-04", audition_time1: "2:45PM-7:30PM", audition_date2: "2024-05-05", audition_time2: "12:30PM-3:00PM", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_address_id: callback_address.id , callback_date1: "2024-05-05", callback_time1: "1:00PM-3:00PM", callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "Auditions will be held in small groups and will consist of physical theatre and creative movement, improvisational activities, and games. -Please wear clothes you can move in. -Be prepared to collaborate and create with others -To prepare: After the group portion, auditionees are invited to share a 1-minute presentation that shows us who you are! It can be a song, a poem, a story, a creative drama game, a puppet show, a joke, anything. Additionally, if you play an instrument, please bring it and prepare a short selection.", how_to_submit: "Please email Ashley at ashleylaverty@kerfuffletvy.com with your resume, headshot or photo, and top two 45-minute time preferences for May 4th: Group A 2:45-3:30PM; Group B 3:45-4:30PM; Group C 4:45-5:30PM; Group D 5:45-6:30PM; Group E 6:45-7:30PM")

Character.create!(audition_id: audition.id, name: "Performer", age: "Open", gender: "Open", ethnicity: "Any/Open", description: " Kerfuffle encourages performers of all ethnicities, gender identities, sexual orientations, sizes, ages, abilities, and experiences to audition.", skills: "Performers should be excellent collaborators. Prior experience or interest in working with and/or teaching very young children and/or devising is preferred, but not required. Each performer will be responsible for devising small group moments, scenes, songs, or games to be shared along the trail. Performers should feel comfortable with close interaction and improvisation with children and families.", notes: nil)


show_address = Address.create!(address1: "Facility Theatre", address2: "1138 N California Ave", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60622")
audition = Audition.create!(name_of_company: "Theatre L'Acadie",  union_status: "Non-Equity", pay_scale: "$200", name_of_show: "The Swan", written_by: "Elizabeth Egloff", director: "Erin Sheets", musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-05-20", tech_startdate: "2024-07-04", previews_startdate: nil, show_startdate: "2024-07-12", show_enddate: "2024-07-27", show_address_id: show_address.id, show_warnings: "", show_description: "Dora Hand lives by herself in a suburb on the Nebraska prairie. She's gone through three husbands and now seems destined to play the lonely mistress to her married milkman, Kevin-until a swan crashes into her living room window and sets Dora on a harrowing journey. She names him Bill, and to all outward appearances, Bill is a charismatic and child-like man. At first endearing himself to Dora like a pet she can train, Bill quickly learns the ropes of being human: speech, dressing, checkers, beer...and love for his mistress. All at once, Dora finds herself dangerously entangled with the swan, whose animal devotion to her threatens her already neglected lover and ultimately her sense of self.", additional_notes: nil, audition_date1: "2024-04-30", audition_time1: nil, audition_date2: "", audition_time2: "", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: "", callback_time1: "", callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: nil, materials_to_prepare: "headshot and resume and a self tape of sides from audition form", how_to_submit: "https://docs.google.com/forms/d/e/1FAIpQLSeaJMRMw0yKVq2cQNg209WeF5TIvUCwQ5dUH7LGD7uoCELoWQ/viewform")

Character.create!(audition_id: audition.id, name: "Understudy - DORA", age: "Open", gender: "Female", ethnicity: "Any/Open", description: "a nurse", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Understudy - KEVIN", age: "Open", gender: "Male", ethnicity: "Any/Open", description: "a milkman", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "Understudy - BILL", age: "Open", gender: "Male", ethnicity: "Any/Open", description: "a swan/man", skills: "Seeking strong movement/physical actors", notes: nil)


audition = Audition.create!(name_of_company: "Pegasus Theatre Chicago",  union_status: "Non-Equity", pay_scale: "Rehearsal Stipend $450, $40 Per Performance", name_of_show: "Dontrell, Who Kissed The Sea", written_by: "", director: "ILesa Duncan", musical_director: nil, choreographer: nil, rehearsal_startdate: "2024-06-09", tech_startdate: "2024-07-07", previews_startdate: "2024-07-11", show_startdate: "2024-07-15", show_enddate: "2024-08-18", show_address_id: nil, show_warnings: "", show_description: "Eighteen-year-old Dontrell Jones the Third decides that it is his duty and destiny to venture into the Atlantic Ocean in search of an ancestor lost during the Middle Passage. But his family is not at all ready to abandon its prized son to the waters of a mysterious and haunting past. Blending poetry, humor, wordplay, and ritual, Dontrell, Who Kissed the Sea is a present-day hero’s quest exploring the lengths and depths we must go to redeem history’s wrongs.", additional_notes: nil, audition_date1: "2024-04-29", audition_time1: nil, audition_date2: "", audition_time2: "", audition_date3: nil, audition_time3: nil, audition_date4: nil, audition_time4: nil, audition_date5: nil, audition_time5: nil, callback_date1: "", callback_time1: "", callback_date2: nil, callback_time2: nil, callback_date3: nil, callback_time3: nil, in_the_room: "Director: ILesa Duncan, Associate Director: India Burton, Casting Director: Kavin Moore, CSA (He/They)", materials_to_prepare: "Slate your name, pronouns and prepare the side(s) for the character you are most interested in. Submissions will be due  March 29th at 11:59pm CT ", how_to_submit: "Please submit your audition via Google Form: https://forms.gle/xWnuPtK4pggXVZRRA")

Character.create!(audition_id: audition.id, name: "DONTRELL JONES III", age: "Late Teens", gender: "Male", ethnicity: "Black", description: "Heir to a haunting and powerful legacy", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "ERIKA", age: "Early 20s", gender: "Female", ethnicity: "White", description: "A lifeguard and Dontrell's soulmate", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "DAD", age: "40s", gender: "Male", ethnicity: "Black", description: "Dontrell's father", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "MOM", age: "40s", gender: "Female", ethnicity: "Black", description: "Dontrell's mother", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "DANIELLE", age: "Late Teens", gender: "Female", ethnicity: "Black", description: "Dontrell's Little Sister", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "SHEA", age: "30s", gender: "Female", ethnicity: "Black", description: "Dontrell's cousin on his father's side", skills: "", notes: nil)
Character.create!(audition_id: audition.id, name: "ROBBIE", age: "Late Teens", gender: "Male", ethnicity: "Black", description: "Dontrell's best friend and an honorary member of the family", skills: "", notes: nil)


 