### User Index
GET http://localhost:3000/users.json

### User Create
POST http://localhost:3000/users.json
Content-Type: application/json

{ 
  "user": {
    "first_name": "Katherine",
    "last_name": "Evans",
    "email": "katevansdev@gmail.com",
    "password": "password",
    "password_confirmation": "password"
  }
}

### Session create
POST http://localhost:3000/users/sign_in.json
Content-Type: application/json

{
  "user":{
    "email": "katevansdev@gmail.com",
    "password": "password"
  }
}


### Password Reset
POST http://localhost:3000/users/password.json
Content-Type: application/json

{
  "user": {
    "email": "evans.katherine.e@gmail.com"
  }
}

### Theater Index
GET http://localhost:3000/theaters.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJjNjcyNzYwZi1kOWExLTQwOTYtYWZmYi1mZmRjYzlhYmI0MWQiLCJzdWIiOiIxMSIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY4NjY2OTg1MywiZXhwIjoxNjg2NzU2MjUzfQ.-aH-gxXQABcywZmIERrvYBUn1mW3DffZLL6eIBfwzMY

### Auditions
GET http://localhost:3000/auditions.json