# BIPOC

Resource.create!({ document_name: nil, organization_name: "Arts Adminstrators of Color", pdf_url: nil, website_url: "https://www.aacnetwork.org/", type: "BIPOC", sub_type: nil, description: "Founded in July 2016, the Arts Administrators of Color Network (AAC) is a service organization that focuses on networking and community building through the arts. We are advocates who continue to fight for equity in the arts through collaborations, forums, and outlets that provide a voice for arts administrators and artists of color where there may not be one.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "BIPOC Leadership Circle", pdf_url: nil, website_url: "https://www.artequity.org/bipoc-lc", type: "BIPOC", sub_type: nil, description: "The BIPOC Leadership Circle is designed to center, support, and address experiences of BIPOC leaders of cultural institutions.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "For The Group", pdf_url: nil, website_url: "https://www.forthegroupchicago.com/", type: "BIPOC", sub_type: nil, description: "We are an anti-racist collective of Chicago-based theatre professionals working to break down the barriers to equitable employment for BIMPOC designers, technicians, staging practitioners, and other production professionals. Our goal is to uplift theatre Practitioners from historically marginalized groups in our industry by providing a web-based platform to make their names, experience, and work known to hiring managers; to promote better hiring practices; and provide resources for anti-racist education.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Community Film Workshop of Chicago", pdf_url: nil, website_url: "https://www.cfwchicago.org/", type: "BIPOC", sub_type: nil, description: "Community Film Workshop of Chicago works in underserved neighborhoods mentoring the next generation of media makers. Our goal is to empower ordinary citizens in the use of media and to provide media arts programming at the Chicago Park District's Harriet Harris Park.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "eta Creative Arts", pdf_url: nil, website_url: "https://www.etacreativearts.org/", type: "BIPOC", sub_type: nil, description: "Some stuff", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: "Alternative Canon", organization_name: "Alternative Canon", pdf_url: "https://docs.google.com/document/d/1HwAHAwU83bW_jSzxbMrqWyyuAYmsOWtqK-7HxKA9yek/mobilebasic?fbclid=IwAR3u2Fp7e_JuAvGHnqjdjlivBxtfqqUIf11W_RKu4hpQXRwSj6-YXdxO1mM#id.b12d9qm89kyv", website_url: nil, type: "BIPOC", sub_type: nil, description: "Non-Western plays, plays by people of color, by women and by queer writers from before 1945.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: "BIPOC Swap List", organization_name: "BIPOC Swap List ", pdf_url: "https://docs.google.com/spreadsheets/d/1hrNaae60biRBsRTgX3oGPuZ7qMliQrBNgPYdJO40c64/htmlview#", website_url: nil, type: "BIPOC", sub_type: nil, description: "A growing list of plays, musicals, and acting method readings by BIPOC playwrights, composers, and theatremakers to “swap” in place of material typically used from the American theatre canon; based on similar themes and/or adaptations. A resource for theatre educators.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Black Playwrights Intiative", pdf_url: nil, website_url: "https://www.blackensembletheater.org/outreach/black-playwrights-intiative/", type: "BIPOC", sub_type: "Black", description: "The Black Playwrights Initiative (BPI) was created in 2005 by Jackie Taylor, Founder and Executive Director of the Black Ensemble Theater. In explaining why the BPI was formulated Ms. Taylor stated; “Chicago has a rich and fertile community of African American Playwrights. There was a need for an organization that focused specifically on these artists as it related to their unique cultural heritage. The BPI is a vehicle that brings us together as a community to share resources and nourish our skills. It is the purpose of the BPI to develop scripts for the Black Ensemble Theater. It is also the purpose of the BPI to increase local and national exposure for our membership.” The BPI also provides training, technological resources and advancement opportunities for Chicago’s African American Playwrights Community.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "African American Arts Alliance of Chicago", pdf_url: nil, website_url: "https://www.aaaachicago.org/", type: "BIPOC", sub_type: "Black", description: "The AAAA is a non-profit service organization dedicated to promoting the performing, visual, literary, technical and design art forms! For almost 30 years, the Alliance has worked to increase the interaction, communication and collaboration within the Black Arts community to promote the continuing development of organizations and individual artists. With support from our advocates, artists and member organizations, the Alliance will continue to nurture the positive images of our members.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Black Film Space", pdf_url: nil, website_url: "https://www.blackfilmspace.com/home", type: "BIPOC", sub_type: "Black", description: "Our mission is to provide skill-enhancing opportunities, community building experiences and knowledge on navigating the film industry for people of African descent.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Sisters in Cinema", pdf_url: nil, website_url: "http://www.sistersincinema.com/", type: "BIPOC", sub_type: "Black", description: "founded in 1997 as an online resource for and about African American women media makers. Today we are a Chicago based 501(c)3 non-profit with an inclusive mission to center and celebrate Black girls, women, and gender nonconforming media makers, providing programs designed to educate, raise visibility, and support and serve our communities.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "The African American Voice Database", pdf_url: nil, website_url: "https://www.aavadb.com/", type: "BIPOC", sub_type: "Black", description: "Established in 2019, the African-American Voice Actor Database is a platform to showcase talented, professional, and authentic African-American voice actors. It is our goal to facilitate connections between amazing talents and agents/voice-seekers. The AAVDB is funded entirely by donations.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Asian Improv aRts Midwest", pdf_url: nil, website_url: "https://www.airmw.org/", type: "BIPOC", sub_type: "AAPI", description: "Asian Improv aRts Midwest’s mission is to build a vital, self-empowered Asian American Community in the Chicago area by advancing the understanding and profile of Asian American cultures through the traditional and contemporary cultural arts.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Asian American Theatre Revue", pdf_url: nil, website_url: "https://www.aatrevue.com/", type: "BIPOC", sub_type: "AAPI", description: "The Revue has tracked Asian American theatre across the world since the early 1990s.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "The Brief History of AAPT Theatre", pdf_url: nil, website_url: "https://www.roundabouttheatre.org/a-brief-history-of-aapi-theatre/", type: "BIPOC", sub_type: "AAPI", description: "This is not an exhaustive timeline, and the definition of what constitutes AAPI theatre can be complex and varied. Included in the entries are links to the websites of some AAPI theatres and arts organizations that have supported and fostered numerous artists throughout the years. We encourage you to continue learning about the rich history of AAPI artists and to support the work of the theatres and art organizations by donating to them and by attending their productions.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "APIDA Arts Festival", pdf_url: nil, website_url: "https://www.apidaarts.org/", type: "BIPOC", sub_type: nil, description: "Their mission is to amplify and unify APIDA makers, creators, artists, and performers of Chicago", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Bubble Tea - Neatworking for Asian American Actors in Chicago", pdf_url: nil, website_url: "https://www.facebook.com/groups/193828444090900", type: "BIPOC", sub_type: "AAPI", description: "Bubble Tea - Networking for Asian American Actors in Chicago Group is exactly that. A safe and positive place for Asian-American actors, models, and artists to help, grow, promote, and network with other Asian-American actors, models, and artists.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "American Indian Center", pdf_url: nil, website_url: "https://www.aicchicago.org/", type: "BIPOC", sub_type: "American Indian", description: "The mission of the American Indian Center of Chicago (AIC) is to promote fellowship among Indian people of all Tribes living in metropolitan Chicago and to create bonds of understanding and communication between Indians and non-Indians in this city; to advance the general welfare of American Indians into the metropolitan community life; to foster the economic advancement of Indian people; to sustain cultural, artistic, and avocational pursuits; and to perpetuate Indian cultural values.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Inner City Muslim Action Network", pdf_url: nil, website_url: "https://www.imancentral.org/", type: "BIPOC", sub_type: "Muslim", description: "The Inner-City Muslim Action Network (IMAN) is a community organization that fosters health, wellness and healing in the inner-city by organizing for social change, cultivating the arts, and operating a holistic health center.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "JCC Chicago Jewish Film Festival", pdf_url: nil, website_url: "https://www.jccfilmfest.jccchicago.org/", type: "BIPOC", sub_type: "Jewish", description: "The JCC Chicago Jewish Film Festival mission is to showcase culturally-diverse, Jewishly-inspired films that will entertain, educate and inspire audiences.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "The Alliance for Jewish Theatre", pdf_url: nil, website_url: "https://www.alljewishtheatre.org/", type: "BIPOC", sub_type: "Jewish", description: "Alliance for Jewish Theatre is a network of international Jewish theatres and theatre artists supporting each other through information-sharing, conferences, and virtual programs.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Latino Cultural Center", pdf_url: nil, website_url: "https://www.latinoculturalcenter.org/", type: "BIPOC", sub_type: "Latinx", description: "We are an organization enriching Chicago’s cultural scene by promoting positive images of Latinos, breaking stereotypes and bringing everyone together to experience all Latino cultures.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Puerto Rican Arts Alliance", pdf_url: nil, website_url: "https://www.praachicago.org/", type: "BIPOC", sub_type: "Latinx", description: "PRAA seeks to impact present and future generations with life changing experiences that will inspire and help them become the best version of themselves. The Latin Music Project and Studio Arts Apprenticeship Program teaches job-skills to under-served teens through the instruction of music, visual arts and providing hands on gallery exhibition and performing arts experience.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Segundo Ruiz Belvis Cultural Center", pdf_url: nil, website_url: "http://segundoruizbelvis.org/", type: "BIPOC", sub_type: "Latinx", description: "One of 40 organizations recently recognized for its contributions to the history, culture, vibrancy, and identity of communities of color in greater Chicago (see Chicago Cultural Treasures), Segundo Ruiz Belvis Cultural Center (SRBCC) is the longest-standing Latino cultural center in Chicago. Established in 1971, it was named in honor of Segundo Ruiz Belvis, a Puerto Rican patriot and member of a secret abolitionist society that freed slave children under Spanish rule. In that spirit, SRBCC realizes its mission to preserve and promote appreciation of the culture and arts of Puerto Rico and Latin America, with a focus on its African heritage.", logo: "logo.url", free_tier: true})



# Disabilities

Resource.create!({ document_name: nil, organization_name: "Chicago Cultural Accessibility Consortium", pdf_url: nil, website_url: "https://www.chicagoculturalaccess.org/", type: "Artists with Disabilities", sub_type: nil, description: "Our mission is to empower Chicago’s cultural spaces to become more accessible to visitors with disabilities.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Chicago Cultural Accessibility Events Calendar", pdf_url: nil, website_url: "https://www.culturalaccesscollaborative.org/events/", type: "Artists with Disabilities", sub_type: nil, description: "Search The Chicago Access Collabrative accessible events calendar!", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "League of Chicago Theatre's Access Calendar", pdf_url: nil, website_url: "https://www.chicagoplays.com/access/", type: "Artists with Disabilities", sub_type: nil, description: "The League of Chicago Theatres is committed to working with Chicago area theatres to make live theatre accessible to everyone. Our calendar enables patrons with disabilities to look for upcoming performances based on their specific access requirements. The calendar includes Touch Tours (TT), ASL-Interpreted (ASL), Audio-Described (AD), Open-Captioned (OC) and Autism-Friendly (AUT) performances. Autism-Friendly performances are relaxed and sensory-friendly theatre experiences designed to be more accessible to those individuals on the autism spectrum or to others with cognitive/developmental disabilities.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: "Disabled Voice Actor Database Form", organization_name: "Disabled Voice Actor Database", pdf_url: nil, website_url: "bit.ly/disabledvoiceactors", type: "Artists with Disabilities", sub_type: nil, description: "We want disabled voice actors to be found so they can authentically tell disabled stories. We also want them to be in the mix when casting directors consider actors of all types for roles. Email disabledvoiceactors@gmail.com with questions.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "A.B.L.E", pdf_url: nil, website_url: "https://www.ableensemble.com/", type: "Artists with Disabilities", sub_type: nil, description: "Our mission is to provide performing arts experiences through which individuals with Down syndrome and other intellectual and developmental disabilities build the confidence and skills to share who they are and all they are A.B.L.E. to do! By placing participants with disabilities in the spotlight, A.B.L.E.’s work strives to shift societal preconceptions about disability, and build more inclusive, empathetic communities.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Tellin' Tales Theatre", pdf_url: nil, website_url: "https://www.tellintales.org/", type: "Artists with Disabilities", sub_type: nil, description: "The mission of Tellin’ Tales Theatre is to shatter barriers between the disabled and non-disabled worlds through the transformative power of personal story. We bring together children and adults from both communities to share their stories in theatrically innovative productions and programs to promote awareness, understanding and acceptance.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Special Gifts Theatre", pdf_url: nil, website_url: "https://www.specialgiftstheatre.org/", type: "Artists with Disabilities", sub_type: nil, description: "Through the performing arts, we work collaboratively to create inclusive and transformative experiences for individuals with disabilities to fully engage in the world.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "The Red Kite Project", pdf_url: nil, website_url: "https://www.chicagochildrenstheatre.org/red-kite-project/", type: "Artists with Disabilities", sub_type: nil, description: "The Red Kite Project at Chicago Children’s Theatre is a series of unique and innovative programs for youth on the autism spectrum and their families, as well as initiatives and productions that make our theatrical and education programming accessible to young people with developmental disabilities and other accessibility needs.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Crip Crap Media", pdf_url: nil, website_url: "https://www.cripcrapmedia.com/", type: "Artists with Disabilities", sub_type: nil, description: "Media about disability, by and for disabled people", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Disability Visibility Project", pdf_url: nil, website_url: "https://www.disabilityvisibilityproject.com/", type: "Artists with Disabilities", sub_type: nil, description: "The Disability Visibility Project is an online community dedicated to creating, sharing, and amplifying disability media and culture.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "PEEP", pdf_url: nil, website_url: "https://www.piventheatre.org/our-community/peep/", type: "Artists with Disabilities", sub_type: nil, description: "PEEP is a theatre ensemble that celebrates and invites artists with developmental disabilities. For nearly two decades, PEEP has provided space and time for creative exploration through improvisation and original storytelling. Players develop process-based theatre and improvisation skills while building deep ensemble awareness. Ensemble members practice taking risks, cultivate their individual voices, and explore how each player contributes to the whole. Any player who has completed one semester is invited to play with the PEEP improv performance ensemble, which specializes in completely improvised original group storytelling.", logo: "logo.url", free_tier: true})


# LGBTQIA+

Resource.create!({ document_name: nil, organization_name: "Josephine Kearns | Gender Consultant & Dramaturg", pdf_url: nil, website_url: "https://www.josephinekearns.com/", type: "LGBTQIA", sub_type: "Transgender, Queer, Intersex", description: "Josie (she/her) is a gender consultant and theatre artist specializing in transgender, queer, and intersex issues. She believes in a thoughtful, empathetic approach with an emphasis on the joys of being queer and trans.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Artemis Singers", pdf_url: nil, website_url: "https://www.artemissingers.org", type: "LGBTQIA", sub_type: "Lesbian", description: "Artemis Singers is a lesbian feminist chorus comprised of women with diverse backgrounds who are dedicated to performing music written or arranged by women. The chorus works to effect positive change in cultural attitudes toward women and women artists, as well as to increase the visibility of lesbian feminists", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "The Chicago Gay Men’s Chorus", pdf_url: nil, website_url: "https://www.facebook.com/ChiGMC?v=info", type: "LGBTQIA", sub_type: "Gay", description: "The Chicago Gay Men’s Chorus (CGMC) has been an integral part of Chicago’s cultural and gay communities for 25 years. In that time, we have entertained audiences across the continent with innovative musical programming exploring everything from love to politics to the sometimes fabulous, sometimes challenging world of being gay—often all at the same time.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Chicago Lesbian and Gay International Film Festival", pdf_url: nil, website_url: "https://www.reelingfilmfestival.org", type: "LGBTQIA", sub_type: "Gay, Lesbian", description: "The mission of Reeling is to recognize the important artistic contributions that lesbian, gay and transgender filmmakers have made to our culture; to educate the general population and sensitize them to lesbian, gay and transgender issues; to investigate the history of LGBTQ film, including the stereotyping that has been a major part of this history; and to counteract this stereotyping with valid, meaningful and diverse portrayals of those in the LGBTQ community.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Windy City Performing Arts", pdf_url: nil, website_url: "https://windycitysings.org/", type: "LGBTQIA", sub_type: nil, description: "Windy City Performing Arts (WCPA) was incorporated in 1983 as the independent not-for-profit umbrella organization for Windy City Gay Chorus, Windy City Slickers, Unison: Windy City Lesbian and Gay Singers, and Aria: Windy City Women’s Ensemble. Windy City Performing Arts exists to create, nurture and maintain performing arts ensembles of the highest level of artistic quality for the purposes of fostering gay and lesbian pride, promoting understanding and compassion for LGBT people, and reaching out to touch the lives of LGBT and mainstream audiences through musical excellence as Chicago’s Premier LGBT Choral Arts Organization.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Non-Binary Monologues", pdf_url: nil, website_url: "https://nonbinarymonologues.wordpress.com/", type: "LGBTQIA", sub_type: "Non-Binary", description: "A collection of monologues written for non-binary actors (actors whose identities lie outside the gender binary of male/female.) Created by Key K. Woodzick.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "Trans Voices Cabaret", pdf_url: nil, website_url: "https://www.transvoicescabaret.com/chicago", type: "LGBTQIA", sub_type: "Transgender, Non-Binary", description: "First and foremost a celebration of trans and gender non-conforming musical theater performers.​ Trans Voices Cabaret CHI is the Chicago extension of the hit NYC show, Trans Voices Cabaret. TVCChi is the first home for transgender/gender nonconforming individuals in the Chicago Musical Theatre World, giving performers a space to perform whatever musical theatre song they wish (regardless of initial gender of the character), and in turn showing the marketability of hiring a trans actor in roles of their true gender.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "The Center on Halsted", pdf_url: nil, website_url: "https://www.centeronhalsted.org/", type: "LGBTQIA", sub_type: nil, description: "Center on Halsted is the Midwest's most comprehensive community center dedicated to advancing community and securing the health and well-being of the Lesbian, Gay, Bisexual, Transgender and Queer (LGBTQ) people of Chicagoland. More than 1,000 community members visit the Center every day, located in the heart of Chicago's Lakeview Neighborhood", logo: "logo.url", free_tier: true})


# Women+

Resource.create!({ document_name: nil, organization_name: "Women’s Theatre Alliance", pdf_url: nil, website_url: "https://www.wtachicago.org/", type: "Women+", sub_type: nil, description: "Women’s Theatre Alliance offers new play development workshops and annual actors showcases as an opportunity for underrepresented genders to get their work in front of producers, directors, agents, and other movers and shakers in the industry.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "StateraArts", pdf_url: nil, website_url: "https://stateraarts.org/", type: "Women+", sub_type: nil, description: "“Mentorship is at the core of Statera's mission of creating pathways that bring women and non-binary people into full and equal participation in the arts.” Statera matches mentors with mentees to foster career development in the Chicago theatre industry.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "League Of Professional Theatre Women", pdf_url: nil website_url: "https://www.theatrewomen.org", type: "Women+", sub_type: nil, description: "The League of Professional Theatre Women champions women in theatre. Our membership includes artists and practitioners of all backgrounds, across multiple disciplines, working in the commercial and non-profit sectors. We advocate for opportunities and visibility for female theatre professionals.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "The International Centre for Women Playwrights", pdf_url: nil, website_url: "https://womenplaywrights.org/", type: "Women+", sub_type: nil, description: "The International Centre for Women Playwrights through networking, mentoring, publications and advocacy, champions women-identified playwrights throughout the world.", logo: "logo.url", free_tier: true})

Resource.create!({ document_name: nil, organization_name: "The Lillies Award", pdf_url: nil, website_url: "https://the-lillys.org/", type: "Women+", sub_type: nil, description: "The Lillys began in the Spring of 2010 as The Lilly Awards, an outlet to honor the work of women in the American theater. The founders are: Julia Jordan, Marsha Norman, and Theresa Rebeck. The organization is named for Lillian Hellman, a pioneering American playwright who famously said “You need to write like the devil and act like one when necessary.", logo: "logo.url", free_tier: true})


# Life Hacks

# Business