User.create!([{first_name: "Test", last_name: "Test", company_id: nil, email: "test@test.com", email_verified: nil, password: "password", phone: nil, date_of_birth: nil, address_id: nil, metadata: nil, last_logged_in_at: "2022-07-01 19:00:40", tos_accepted_at: nil, union_status: nil, ethnicity: nil, pronouns: "She/Her/Hers", gender: nil, height: nil, eye_color: nil, hair_color: nil, vocal_range: nil, instruments_played: nil, talents: nil, performance_types: nil, agency: nil, manager: nil, professional_website: nil, headshot_url: nil, resume_url: nil},{first_name: "ATLAS", last_name: "User", company_id: nil, email: "info@chiartistatlas.com", email_verified: nil, password: "$2a$12$hEawzcGxgJEV/C2elnMOPeh1HM6N3eVUXpWewhKb3ZvBmljs.RMvK", phone: nil, date_of_birth: nil, address_id: nil, metadata: nil, last_logged_in_at: "2022-07-01 19:04:43", tos_accepted_at: nil, union_status: nil, ethnicity: nil, pronouns: "they/them", gender: nil, height: nil, eye_color: nil, hair_color: nil, vocal_range: nil, instruments_played: nil, talents: nil, performance_types: nil, agency: nil, manager: nil, professional_website: nil, headshot_url: nil, resume_url: nil}])

address = Address.create!(address1: "2515 Central Park Ave", address2: nil, address3: nil, city: "Evanston", state: "IL", country: "US", postal_code: "60201")
second_act = Theater.create!(name: "2nd Act Players", business_address_id: address.id, performance_address_id: address.id, website: "evanston2ndactplayers.com", contact_name: "John N. Frank", contact_email: "johnnfrank@evanston2ndactplayers.com", casting_director: nil, casting_email: nil, notes: nil, season_type: "Stage Drama", union_status: "Non-Equity", image_url: nil, active: true, mission: "Our mission is to foster emerging talent through performances that explore 2nd acts in people’s lives.")

address = Address.create!(address1:"1531 N Wells St", address2: nil, address3: nil, city: "Chicago", state: "IL", postal_code: "60610")
red_orchard = Theater.create!(name: "A Red Orchid", business_address_id: address.id, performance_address_id: address.id, website: "www.aredorchidtheatre.org", contact_name: "Abigail Madden", contact_email: "abigail@aredorchidtheatre.org", casting_director: "Mierka Girten", casting_email: nil, notes: "Ensemble Theatre", season_type: "Stage Drama", union_status: "Equity", image_url: nil, active: true, mission: "A Red Orchid Theatre is an ensemble of artists dedicated to the proliferation of live theatre in the modern world. We believe that theatre is the greatest sustenance for the human spirit, and we approach our work with a palpable sense of social compassion, aesthetic rigor, and honesty. By presenting new plays from all over the world and by reviving insightful works from the past that bear new relevance today, we aim to seek out and build new audiences for the modern stage.")

performance_address = Address.create!(address1:"The Den Theater", address2:"1331 N Milwaukee Ave", address3: nil, city: "Chicago", state: "IL", postal_code: "60622")
business_address = Address.create!(address1:"5252 N Broadway", address2: nil, address3: nil, city: "Chicago", state: "IL", postal_code: "60640")
about_face = Theater.create!(name: "About Face Theatre", business_address_id: business_address.id, performance_address_id: performance_address.id, website: "www.aboutfacetheatre.com", contact_name: "Megan Carney", contact_email: "megan@aboutfacetheatre.com", casting_director: "Megan Carney", casting_email: "megan@aboutfacetheatre.com", notes: nil, season_type: "Stage Drama", union_status: "Equity", image_url: nil, active: true, mission: "About Face Theatre advances LGBTQ+ equity through community building, education, and performance.")

theater_in_the_dark = Theater.create!(name: "A Theater In The Dark", business_address_id: nil, performance_address_id: address.id, website: "https://www.atheatreinthedark.com/", contact_name: nil, contact_email: nil, casting_director: nil, casting_email: nil, notes: nil, season_type: nil, union_status: nil, image_url: nil, active: true, mission: "A Theater In The Dark creates stories through sound, producing both streaming audio plays and in-person in-the-dark theatre experiences. Proudly established in Chicago, 2019. Our stories combine the written word, human voices, rich soundscapes, and original music.")

address = Address.create!(address1:"1333 West Devon Avenue", address2: nil, address3: nil, city: "Chicago", state: "IL", postal_code:"60660")
accidental = Theater.create!(name: "Accidental Shakespeare", business_address_id: address.id, performance_address_id: nil, website: "https://accidentalshakespeare.org/", contact_name: nil, contact_email: "contact@accidentalshakespeare.org", casting_director: nil, casting_email: "accshakes@gmail.com", notes: nil, season_type: "Stage Drama, Classical", union_status: "Non-Equity", image_url: nil, active: true, mission: "Accidental Shakespeare is an ensemble theatre company that thoughtfully explores challenging plays, to forge connections between classical themes and contemporary culture in intimate settings.")

address = Address.create!(address1:"2707 N Laramie Ave", address2: nil, address3: nil, city: "Chicago", state: "IL", postal_code: "60639")
aguijon = Theater.create!(name: "Aguijon Theatre Company", business_address_id: address.id, performance_address_id: address.id, website: "http://aguijontheater.org/", contact_name: nil, contact_email: "rvargas@aguijontheater.org", casting_director: nil, casting_email: nil, notes: "Latino and Spanish-language Productions", season_type: "Stage Drama", union_status: "Non-Equity", image_url: nil, active: true, mission: "Aguijón’s mission is to promote and foster theater which addresses social issues affecting the U.S. Latino community specifically and the general population at large; and to build bridges of communication and understanding among the new Latino generations, instilling in them pride in the richness of their cultural heritage. The Company produces classic and contemporary plays and, through artistic collaborations, literary adaptations and original works, exposes Latino and non-Latino audiences to high quality Spanish-language theatre for educational and literary purposes.")

address = Address.create!(address1:"5315 N Clark", city: "Chicago", state: "IL", postal_code: "60640")
annoyance = Theater.create!(name: "Akvavit Theatre", business_address_id: address.id, performance_address_id: nil, website: "https://www.chicagonordic.org/", contact_name: nil, contact_email: "info@chicagonordic.org", casting_director: nil, casting_email: "casting@chicagonordic.org", notes: "Focus on Nordic Plays and translations", season_type: "Stage Drama", union_status: "Non-Equity", image_url: nil, active: true, mission: "Akvavit Theatre is haunted by Nordic visions: deep forests and ice-blue seas, the patience of the glacier, the sudden fury of the volcano, the arctic light and silence. Seeking the universal through the voices of contemporary Nordic playwrights, Akvavit Theatre is a kind of homecoming, a connecting back to the lands whose people and cultures have for generations been a part of the great prairies of North America that we call home. And like our namesake beverage, Akvavit brings a “strong spirit” to the work that we produce. Skål, Skál, Kippis!")

address = Address.create!(address1:"4809 N Ravenswood Ave", address2: "Suite 221", city: "Chicago", state: "IL", postal_code: "60640")
annoyance = Theater.create!(name: "American Blues Theatre", business_address_id: address.id, performance_address_id: nil, website: "www.americanbluestheatre.com", contact_name: "Wendy Whiteside", contact_email: "wendyw@americanbluestheater.com", casting_director: "Wendy Whiteside", casting_email: "info@americanbluestheater.com", notes: nil, season_type: "Stage Drama", union_status: "Equity", image_url: nil, active: true, mission: "American Blues Theater is committed to developing the classic plays and musicals of tomorrow. More than half of our mainstage productions are world and Chicago premieres. Our new play development consists of a variety of programs – including world and Chicago premieres, the nationally-recognized Blue Ink Playwriting Award, Blueprint play development, and annual Ripped: the Living Newspaper Festival of new short-plays.")

address = Address.create!(address1:"851 W Belmont Ave", city: "Chicago", state: "IL", postal_code: "60657")
annoyance = Theater.create!(name: "Annoyance Theatre", business_address_id: address.id, performance_address_id: address.id, website: "https://www.theannoyance.com/shows", contact_name: "Julia Morales", contact_email: "julia@theannoyance.com", casting_director: nil, casting_email: nil, notes: nil, season_type: "Comedy", union_status: "Non-Equity", image_url: nil, active: true, mission: "For over 30 years, The Annoyance Theatre has created some of Chicago’s finest comedy. Home of the longest-running musical Co-ed Prison Sluts, The Annoyance uses improvisation to create new and original plays, musicals, sketch-comedy and more in a vibrant, creative atmosphere. All are welcome at The Annoyance (over the age of 14), and while there, they may use the bathroom that fits their gender identity.")

business_address = Address.create!(address1:"1212 W Balmoral Ave", city: "Chicago", state: "IL", postal_code: "60640")
performance_address = Address.create!(address1:"Theater Wit", address2: "1229 W Belmont Ave", city: "Chicago", state: "IL", postal_code: "60657")
artemisia = Theater.create!(name: "Artemisia, A Chicago Theatre", business_address_id: business_address.id, performance_address_id: performance_address.id, website: "www.artemisiatheatre.org", contact_name: "Julie Proudfoot", contact_email: "artemisiatheatre@gmail.com", casting_director: "Marissa Padilla", casting_email: nil, notes: "Productions centered on women's interests/issues", season_type: "Stage Drama", union_status: "Non-Equity", image_url: nil, active: true, mission: "Artemisia produces plays that empower women, creating career-altering opportunities for female identifying theatre artists of all racial and ethnic backgrounds; sexual orientations and identities; economic status; ages and disabilities. We make women heroes of their own lives by sharing their stories and amplifying their voices. We invite anyone and everyone who wants to empower women to join us as artists and audience. Artemisia aims to be at the forefront of the fight for women and female-identifying people through outstanding performances that push the envelope. From world premieres to the virtual stage, our mission is and will always be to better our world for women and female-identifying people.")

address = Address.create!(address1:"1230 W Chase Ave", address2: "#3" city: "Chicago", state: "IL", postal_code: "60626")
beverly_arts = Theater.create!(name: "Babes with Blades Theatre Company", business_address_id: address.id, performance_address_id: nil, website: "https://babeswithblades.org/", contact_name: "Haley Rice and Leigh Barrett", contact_email: "artistic@babeswithblades.org", casting_director: nil, casting_email: "casting@babeswithblades.org", notes: "Productions with a focus on women's interest, stage combat", season_type: "Stage Drama", union_status: "Non-Equity", image_url: nil, active: true, mission: "Babes With Blades Theatre Company uses stage combat to place women and their stories center stage. Through performance, script development, training, and outreach, our ensemble creates theatre that explores the wide range of the human experience, and cultivates broader perspectives in the arts community and in society as a whole.")

address = Address.create!(address1:"2407 W 111th Street", city: "Chicago", state: "IL", postal_code: "60655")
beverly_arts = Theater.create!(name: "Beverly Arts Center", business_address_id: address.id, performance_address_id: address.id, website: "https://beverlyartcenter.org/", contact_name: "Carly Bishop", contact_email: "carly@beverlyartcenter.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Stage Drama", union_status: "Non-Equity", image_url: nil, active: true, mission: "The Beverly Arts Center is a vibrant and multifaceted not-for-profit organization serving the Chicago metro area with high-quality programs in dance, visual arts, music, film and theater. The 40,000 square foot space houses a 400-seat theatre, art gallery, exhibition spaces, music and dance studios, art classrooms and event rental spaces including a courtyard and light-filled atrium. Founded in 1967 and located in Chicago’s historic Beverly/Morgan Park neighborhood, the BAC is also home to an extensive community outreach program.")

address = Address.create!(address1:"The Baer Theatre", address2: "2153 W 111th St", city: "Chicago", state: "IL", postal_code: "60643")
beverly_theater = Theater.create!(name: "Beverly Theatre Guild", business_address_id: address.id, performance_address_id: address.id, website: "http://www.beverlytheatreguild.org/", contact_name: nil, contact_email: nil, casting_director: nil, casting_email: nil, notes: "No Pay", season_type: "Stage Drama", union_status: "Non-Equity", image_url: nil, active: true, mission: "Chicago’s oldest community theatre company, with roots going back to 1929. incorporated in its present form in 1963. Present 3 – 4 productions each year, including musicals, dramas, comedies and revues. All roles are cast at open auditions. The Beverly Theatre Guild presents a variety of classics and contemporary works, including world premieres.")

address = Address.create!(address1:"3449 N Elaine Pl", city: "Chicago", state: "IL", postal_code: "60657")
black = Theater.create!(name: "Black Button Eyes Productions", business_address_id: address.id, performance_address_id: nil, website: "https://www.blackbuttoneyes.com/", contact_name: nil, contact_email: nil, casting_director: nil, casting_email: nil, notes: nil, season_type: "Stage Drama, Musicals", union_status: "Non-Equity", image_url: nil, active: true, mission: "Black Button Eyes Productions’ mission is to bring to Chicago premieres and seldom-seen works containing elements of fantasy, in which the magical and surreal invade reality.")

address = Address.create!(address1:"4450 N Clark St", city: "Chicago", state: "IL", postal_code: "60640")
black = Theater.create!(name: "Black Ensemble Theater", business_address_id: address.id, performance_address_id: address.id, website: "www.blackensembletheatre.org", contact_name: nil, contact_email: nil, casting_director: "Jackie Taylor", casting_email: nil, notes: "Productions centered on African American interests", season_type: "Stage Drama, Musicals", union_status: "Equity", image_url: nil, active: true, mission: "The mission of the Black Ensemble Theater is to eradicate racism and its damaging effects upon our society through the utilization of theater arts. BE is the only theater in the nation whose mission is to eradicate racism. We utilize theater and educational outreach programs to bring races together in a community which embraces similarities and fosters dialogue, understanding and acceptance.")

blank = Theater.create!(name: "Blank Theatre", business_address_id: nil, performance_address_id: address.id, website: "https://www.blanktheatrecompany.org/", contact_name: nil, contact_email: "info@blanktheatrecompany.org", casting_director: "Dustin Rothbart", casting_email: nil, notes: nil, season_type: "Stage Drama", union_status: "Non-Equity", image_url: nil, active: true, mission: "Blank Theatre Company sheds light on under-heard stories and themes by re-examining contemporary classics. We are as many voices as we are people, and we work to engage Chicago artists and audiences in theatre that is both timely and timeless.")

business_address = Address.create!(address1:"340 W Diversey Pkwy", address2: "2936 N Southport Ave", city: "Chicago", state: "IL", postal_code: "60657")
performance_address = Address.create!(address1:"The Athenaeum", address2: "#1717", city: "Chicago", state: "IL", postal_code: "60657")
bluebird = Theater.create!(name: "Bluebird Arts", business_address_id: business_address.id, performance_address_id: performance_address.id, website: "https://www.bluebirdarts.org/", contact_name: nil, contact_email: "info@bluebirdarts.org", casting_director: nil, casting_email: nil, notes: "Russian Interests", season_type: "Stage Drama", union_status: "Non-Equity", image_url: nil, active: true, mission: "Bluebird Arts is a nonprofit organization whose purpose is to enrich, educate and entertain our community by sharing intimate stories of the human condition, focusing on the genuine problems of real people. We showcase Chicago’s talent by promoting cross cultural exchange, taking Chicago theatre and artists to Europe and bringing European theatre, to the Chicago community. We serve both the English and Russian speaking populations by producing plays in both English and Russian and translating English language plays into Russian and Russian language plays into English.")

business_address = Address.create!(address1:"PO Box 409267", city: "Chicago", state: "IL", postal_code: "60640")
performance_address = Address.create!(address1:"Greenhouse Theatre", address2: "2257 N Lincoln Ave", city: "Chicago", state: "IL", postal_code: "60614")
boho = Theater.create!(name: "Boho Theatre", business_address_id: business_address.id, performance_address_id: performance_address.id, website: "http://bohotheatre.com/", contact_name: nil, contact_email: "info@bohotheatre.com", casting_director: "Molly Layton and Adam Hill", casting_email: "auditions@bohotheatre.com", notes: nil, season_type: "Stage Drama", union_status: "Non-Equity", image_url: nil, active: true, mission: "BoHo Theatre seeks to create a shared community of artists and patrons in which all members are moved through art to make thoughtful, well-examined, caring relationships the highest priority in their lives.")

business_address = Address.create!(address1:"PO Box 5976", city: "Naperville", state: "IL", postal_code: "60567")
performance_address = Address.create!(address1:"31 S Ellsworth St", city: "Naperville", state: "IL", postal_code: "60540")
broken = Theater.create!(name: "BrightSide Theatre", business_address_id: business_address.id, performance_address_id: performance_address.id, website: "https://brightsidetheatre.com/", contact_name: nil, contact_email: "info@brightsidetheatre.com", casting_director: nil, casting_email: nil, notes: nil, season_type: nil, union_status: "Non-Equity", image_url: nil, active: true, mission: "BrightSide Theatre is committed to Enlighten, Educate, and Entertain through comedies and inspirational stories from across the globe. A unique blend of award-winners, premieres, modern works and timeless classics meant to reflect upon and inform our community will inhabit BrightSide’s stage.")

business_address = Address.create!(address1:"PO Box 2608", city: "Glen Ellyn", state: "IL", postal_code: "60138")
performance_address = Address.create!(address1:"425 Fawell Blvd", city: "Glen Ellyn", state: "IL", postal_code: "60137")
buffalo = Theater.create!(name: "Buffalo Theatre Ensemble", business_address_id: business_address.id, performance_address_id: performance_address.id, website: "https://btechicago.com", contact_name: nil, contact_email: "buffalotheater@btechicago.com", casting_director: "Amelia Barrett", casting_email: "submissions@btechicago.com", notes: nil, season_type: "Stage Drama", union_status: "Equity", image_url: nil, active: true, mission: "BTE is a place for artists, students and community members to celebrate live theatre. It is your theatre because BTE is a part of the structure of the community – both the educational component of College of DuPage and the culture and life of DuPage County. Every performance nurtures a shared experience, enriching each of us.")

address = Address.create!(address1:"100 S Racine Ave", city: "Chicago", state: "IL", postal_code: "60607")
cct = Theater.create!(name: "Chicago Children's Theatre", business_address_id: address.id, performance_address_id: address.id, website: "https://chicagochildrenstheatre.org/", contact_name: nil, contact_email: "info@chicagochildrenstheatre.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Children's Theatre", union_status: "Equity", image_url: nil, active: true, mission: "Chicago Children’s Theatre aspires to enrich our community through diverse and significant theatrical programming that engages and inspires the child in all of us. The vision of Chicago Children’s Theatre is to be the City of Chicago’s premier professional theatre company dedicated to: Creating awe-inspiring theatrical productions and programs for our communities Engaging our broader communities through inclusion and accessibility Inspiring young people and families to lead lives of adventure, courage, and curiosity.")

business_address = Address.create!(address1:"1650 W Foster Ave", city: "Chicago", state: "IL", postal_code: "60640")
performance_address = Address.create!(address1:"Ebenezer Lutheran Church", address2: "1650 W Foster Ave", city: "Chicago", state: "IL", postal_code: "60640") 
cde = Theater.create!(name: "Chicago Danztheatre Ensemble", business_address_id: business_address.id, performance_address_id: performance_address.id, website: "https://www.danztheatre.org", contact_name: nil, contact_email: "info@danztheatre.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Stage Drama", union_status: "Equity", image_url: nil, active: true, mission: "Chicago Danztheatre Ensemble challenges, engages and inspires audiences both onstage and in the classroom, through innovative, multidisciplinary storytelling in the genre of Tanztheatre, “which unites all art media and to achieve an all-embracing, radical change in humankind.” As an Ensemble, we collaboratively create thought-provoking arts performances and educational outreach programs incorporating elements of theatre, music, movement, visual arts and literary text.")

address = Address.create!(address1:"70 E Lake St", address2: "Unit 415", city: "Chicago", state: "IL", postal_code: "60601") 
cot = Theater.create!(name: "Chicago Opera Theater", business_address_id: address.id, performance_address_id: nil, website: "https://www.chicagooperatheater.org/", contact_name: nil, contact_email: "info@cot.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Opera", union_status: nil, image_url: nil, active: true, mission: "Chicago Opera Theater (COT) is a nationally recognized opera company based in Chicago. COT expands the tradition of opera as a living art form, with an emphasis on Chicago premieres, including new contemporary operas for a 21st century audience.")

#   {name: "Chicago Shakespeare Theatre", business_address_id: nil, performance_address_id: nil, website: "www.chicagoshakes.com", contact_name: "Hannah Kennedy", contact_email: "hkennedy@chicagoshakes.com", casting_director: "Casting Associate/Casting Director: Bob Mason", casting_email: nil, notes: nil, season_type: "Classical, Musical", union_status: "Equity", image_url: nil, active: true},
#   {name: "Chicago Youth Shakespeare", business_address_id: nil, performance_address_id: nil, website: "https://www.chicagoyouthshakespeare.org/", contact_name: nil, contact_email: nil, casting_director: nil, casting_email: nil, notes: "Do we need this?? Only for kids", season_type: "Children's Theatre", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Children's Theatre of Winnetka", business_address_id: nil, performance_address_id: nil, website: "https://www.childrenstheatrewinnetka.com/", contact_name: nil, contact_email: nil, casting_director: nil, casting_email: nil, notes: "Only for kids ", season_type: "Children's Theatre", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Citadel Theatre", business_address_id: nil, performance_address_id: nil, website: "https://www.citadeltheatre.org/", contact_name: "Scott Phelps", contact_email: "scottp@citadeltheatre.org", casting_director: "Casting: Ellen Phelps (Managing Director) ", casting_email: "auditions@citadeltheatre.org", notes: nil, season_type: "Stage Drama, Musical, Children's Theatre", union_status: "Equity", image_url: nil, active: true},
#   {name: "City Lit Theater Company", business_address_id: nil, performance_address_id: nil, website: "https://www.citylit.org/", contact_name: "Terry McCabe", contact_email: "tmccabe@citylit.org", casting_director: nil, casting_email: "auditions@citylit.org ", notes: nil, season_type: "Stage Drama, Musical", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Collaboraction", business_address_id: nil, performance_address_id: nil, website: "https://www.collaboraction.org/", contact_name: nil, contact_email: "info@collaboraction.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Stage Drama, Children's Theatre", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Compass Creative Dramatics", business_address_id: nil, performance_address_id: nil, website: "http://www.ccdramatics.com/", contact_name: nil, contact_email: "leadtheway@ccdramatics.com", casting_director: nil, casting_email: nil, notes: nil, season_type: "Children's Theatre", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Connective Theatre Company", business_address_id: nil, performance_address_id: nil, website: "https://www.connectivetheatrecompany.com/", contact_name: nil, contact_email: "connectivetheatrecompany@gmail.com", casting_director: "Rachel Schulz, casting director, at ", casting_email: "connectivecasting@gmail.com", notes: nil, season_type: "Stage Drama", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Congo Square Theatre Company", business_address_id: nil, performance_address_id: nil, website: "https://www.congosquaretheatre.org/", contact_name: nil, contact_email: "Info@congosquaretheatre.org", casting_director: nil, casting_email: nil, notes: "African American Interests", season_type: "Stage Drama", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Conspirators, The", business_address_id: nil, performance_address_id: nil, website: "http://conspirewithus.org/", contact_name: nil, contact_email: "manifesto@conspirewithus.org", casting_director: nil, casting_email: "conspire@conspirewithus.org", notes: nil, season_type: "Stage Drama", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Chicago Symphony Orchestra", business_address_id: nil, performance_address_id: nil, website: "https://cso.org", contact_name: nil, contact_email: nil, casting_director: nil, casting_email: nil, notes: "Do we need this?? ", season_type: nil, union_status: nil, image_url: nil, active: true},
#   {name: "Corn Productions ", business_address_id: nil, performance_address_id: nil, website: "https://www.cornservatory.org/", contact_name: nil, contact_email: "cornproductions@gmail.com", casting_director: nil, casting_email: nil, notes: nil, season_type: "Comedy", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Court Theatre", business_address_id: nil, performance_address_id: nil, website: "www.courttheatre.org", contact_name: nil, contact_email: "info@courttheatre.org", casting_director: "Casting Director: Becca McCracken", casting_email: nil, notes: nil, season_type: "Plays, Classical", union_status: "Equity", image_url: nil, active: true},
#   {name: "CPA Theatricals", business_address_id: nil, performance_address_id: nil, website: "http://cpatheatricals.org/", contact_name: nil, contact_email: "info@cpatheatricals.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Theatre for Young Audiences; Musicals; Female Centered", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Definition Theatre ", business_address_id: nil, performance_address_id: nil, website: "https://www.definitiontheatre.org/", contact_name: nil, contact_email: "info@definitiontheatre.org", casting_director: nil, casting_email: "casting@definitiontheatre.org", notes: nil, season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Drunk Shakespeare", business_address_id: nil, performance_address_id: nil, website: "http://www.drunkshakespeare.com/", contact_name: nil, contact_email: "chicago@drunkshakespeare.com", casting_director: nil, casting_email: nil, notes: nil, season_type: "Plays, Classical; Avante Gard", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Drury Lane Theatre", business_address_id: nil, performance_address_id: nil, website: "https://www.drurylanetheatre.com", contact_name: nil, contact_email: "contact form ", casting_director: nil, casting_email: nil, notes: nil, season_type: "Plays; Musicals", union_status: "Union", image_url: nil, active: true},
#   {name: "Eclipse Theatre Company", business_address_id: nil, performance_address_id: nil, website: "www.eclipsetheatre.com", contact_name: "Nathaniel Swift", contact_email: "nswift@eclipsetheatre.com", casting_director: "Casting: Nathaniel Swift", casting_email: nil, notes: nil, season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Edge of the Wood Resident Theater", business_address_id: nil, performance_address_id: nil, website: "http://edgeofthewood.com/", contact_name: nil, contact_email: "info@edgeofthewood.com", casting_director: nil, casting_email: nil, notes: "kids classes?? ", season_type: "Theatre by Young Performers; Musicals", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Factory Theater, The", business_address_id: nil, performance_address_id: nil, website: "http://thefactorytheater.com/", contact_name: "Timothy Camos ", contact_email: "timothycamos@thefactorytheater.com", casting_director: "Brittney Brown and Anthony Tournis", casting_email: "casting@thefactorytheater.com", notes: nil, season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Filament Theatre", business_address_id: nil, performance_address_id: nil, website: "http://www.filamenttheatre.org/", contact_name: nil, contact_email: "Contact form ", casting_director: nil, casting_email: nil, notes: nil, season_type: "Theatre for Young Audiences; Musicals; Avante Gard, Immersive", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "First Floor Theater", business_address_id: nil, performance_address_id: nil, website: "https://www.firstfloortheater.com/", contact_name: "Hutch Pimentel", contact_email: "hutchpimentel@firstfloortheater.com", casting_director: "Casting: Catherine Miller ", casting_email: nil, notes: "Performs at The Den", season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "First Folio Theatre", business_address_id: nil, performance_address_id: nil, website: "www.firstfolio.org", contact_name: "David Rice ", contact_email: "drice@firstfolio.org", casting_director: "Casting: David Rice", casting_email: nil, notes: nil, season_type: "Plays, Classical", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Fleetwood-Jourdain Theatre", business_address_id: nil, performance_address_id: nil, website: "https://www.cityofevanston.org/about-evanston/arts-and-culture/theatre/fleetwood-jourdain-theatre#ad-image-0", contact_name: nil, contact_email: "fjtheatre@cityofevanston.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Free Street Theater", business_address_id: nil, performance_address_id: nil, website: "https://freestreet.org/", contact_name: nil, contact_email: "info@freestreet.org", casting_director: nil, casting_email: nil, notes: "4346 S Ashland Ave Chicago, IL 60609", season_type: "Theatre by Young Performers; Avante Garde", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Fremont Street Theater Company", business_address_id: nil, performance_address_id: nil, website: "https://www.fremontstreettheater.com/", contact_name: nil, contact_email: "madeline.franklin@fremontstreettheater.com", casting_director: nil, casting_email: nil, notes: nil, season_type: "Musicals ", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Ghostlight Ensemble Theatre Company", business_address_id: nil, performance_address_id: nil, website: "http://www.ghostlightensemble.com", contact_name: nil, contact_email: "info@ghostlightensemble.com", casting_director: nil, casting_email: nil, notes: nil, season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Gilbert and Sullivan Opera Company", business_address_id: nil, performance_address_id: nil, website: "http://www.gilbertandsullivanoperacompany.org/", contact_name: nil, contact_email: "Contact form ", casting_director: nil, casting_email: nil, notes: nil, season_type: "Opera ", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Golden Ticket Productions", business_address_id: nil, performance_address_id: nil, website: "https://goldenticketproductions.org", contact_name: nil, contact_email: "info@goldenticketproductions.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Musicals ", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Goodman Theatre", business_address_id: nil, performance_address_id: nil, website: "www.goodmantheatre.org", contact_name: nil, contact_email: "Info@GoodmanTheatre.org", casting_director: "Casting Director: Lauren Port", casting_email: "Casting@GoodmanTheatre.org", notes: nil, season_type: "Plays", union_status: "Union", image_url: nil, active: true},
#   {name: "Griffin Theatre Company", business_address_id: nil, performance_address_id: nil, website: "https://griffintheatre.com/", contact_name: "William Massolia", contact_email: "bmassolia@gmail.com", casting_director: nil, casting_email: "griffincasting@gmail.com", notes: nil, season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Haven Chicago", business_address_id: nil, performance_address_id: nil, website: "https://havenchi.org/", contact_name: nil, contact_email: "info@havenchi.org", casting_director: "Casting Director: Nik Whitcomb, Marika Mashburn", casting_email: "casting@havenchi.org", notes: nil, season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Hell in a Handbag Productions", business_address_id: nil, performance_address_id: nil, website: "https://www.handbagproductions.org/", contact_name: nil, contact_email: "handbagproductions@gmail.com", casting_director: nil, casting_email: "handbagproductions@gmail.com", notes: nil, season_type: "Musicals; Comedy", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Her Story Theater", business_address_id: nil, performance_address_id: nil, website: "http://www.herstorytheater.org/", contact_name: "Mary Bonnett", contact_email: "chiwriter7@gmail.com", casting_director: nil, casting_email: "chiwriter7@gmail.com", notes: nil, season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "High Concept Labs", business_address_id: nil, performance_address_id: nil, website: "http://highconceptlaboratories.org/ (EXPIRED?)", contact_name: nil, contact_email: nil, casting_director: nil, casting_email: nil, notes: "Arts services organization and flexible space with artist residency program", season_type: "Avante Garde; Devised Work", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Hubbard Street Dance Chicago", business_address_id: nil, performance_address_id: nil, website: "https://www.hubbardstreetdance.com/", contact_name: nil, contact_email: "info@hubbardstreetdance.com", casting_director: nil, casting_email: nil, notes: "Video auditions accepted during winter through an online profile", season_type: "Dance", union_status: nil, image_url: nil, active: true},
#   {name: "Idle Muse Theatre Company", business_address_id: nil, performance_address_id: nil, website: "http://www.idlemuse.org/", contact_name: "Evan Jackson", contact_email: "ejackson@idlemuse.org", casting_director: nil, casting_email: "submissions@idlemuse.org", notes: nil, season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Improv Playhouse", business_address_id: nil, performance_address_id: nil, website: "http://www.improvplayhouse.com/", contact_name: nil, contact_email: "info@improvplayhouse.com", casting_director: nil, casting_email: nil, notes: "Training center for youth and adults with locations in Libertyville and Highland Park", season_type: "Comedy; Improv.", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "International Voices Project", business_address_id: nil, performance_address_id: nil, website: "https://www.ivpchicago.org/", contact_name: "Patrizia Acerra", contact_email: "info@ivpchicago.org", casting_director: nil, casting_email: nil, notes: nil, season_type: nil, union_status: nil, image_url: nil, active: true},
#   {name: "Interrobang Theatre Project", business_address_id: nil, performance_address_id: nil, website: "http://interrobangtheatreproject.com/", contact_name: "Georgette Verdin", contact_email: "georgette@interrobangtheatreproject.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Intrinsic Theatre Company", business_address_id: nil, performance_address_id: nil, website: "http://www.intrinsictheatrecompany.com/", contact_name: "Bradley Hamilton", contact_email: "bradley@intrinsictheatrecompany.com", casting_director: nil, casting_email: "casting@intrinsictheatrecompany.com", notes: nil, season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Invictus Theatre Company", business_address_id: nil, performance_address_id: nil, website: "https://www.invictustheatreco.com/", contact_name: "Charles Askenaizer", contact_email: "invictustheatreco@gmail.com", casting_director: nil, casting_email: "casting@invictustheatre.com", notes: nil, season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Jackalope Theatre Company", business_address_id: nil, performance_address_id: nil, website: "www.jackalopetheatre.org", contact_name: "Kaiser Ahmed", contact_email: "jackalope@Jackalopetheatre.org", casting_director: "Casting Director: Catherine Miller", casting_email: "casting@jackalopetheatre.org", notes: nil, season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Jedlicka Performing Arts Center", business_address_id: nil, performance_address_id: nil, website: "https://www.jpactheatre.com/", contact_name: nil, contact_email: "jedlickainfo@morton.edu", casting_director: nil, casting_email: nil, notes: "On campus of Morton College. You can auditon", season_type: nil, union_status: nil, image_url: nil, active: true},
#   {name: "Kokandy Productions", business_address_id: nil, performance_address_id: nil, website: "https://www.kokandyproductions.com/", contact_name: "Scot Kokandy", contact_email: "scot@kokandyproductions.com", casting_director: nil, casting_email: "casting@kokandyproductions.com", notes: nil, season_type: "Musicals", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Lookingglass Theatre Company", business_address_id: nil, performance_address_id: nil, website: "www.lookingglasstheatre.org", contact_name: "Heidi Stillman", contact_email: "hstillman@lookingglasstheatre.org", casting_director: "Casting: Raymond Fox", casting_email: "casting@lookingglasstheatre.org", notes: nil, season_type: "Plays; Avante Garde", union_status: "Union", image_url: nil, active: true},
#   {name: "Lyric Opera of Chicago", business_address_id: nil, performance_address_id: nil, website: "https://www.lyricopera.org/", contact_name: "Magda Krance", contact_email: "mkrance@lyricopera.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Opera", union_status: nil, image_url: nil, active: true},
#   {name: "Madison Street Theatre", business_address_id: nil, performance_address_id: nil, website: "https://www.mstoakpark.com/", contact_name: nil, contact_email: "rentals@mstoakpark.com", casting_director: nil, casting_email: nil, notes: "I think this is a venue with rental spaces?", season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "MadKap Productions", business_address_id: nil, performance_address_id: nil, website: "https://skokietheatre.org/madkap.html", contact_name: "Wendy Kaplan", contact_email: "Wendy@madkapproductions.com", casting_director: nil, casting_email: "wendy@madkapproductions.com", notes: nil, season_type: "Plays", union_status: "Non-Union", image_url: nil, active: true},
#   {name: "Three Brothers Theatre", business_address_id: nil, performance_address_id: nil, website: "https://threebrotherstheatre.com/", contact_name: nil, contact_email: "3brotherstheatre@gmail.com", casting_director: nil, casting_email: nil, notes: "(224) 419-4325", season_type: "Plays ", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Marriott Theatre", business_address_id: nil, performance_address_id: nil, website: "https://www.marriotttheatre.com/", contact_name: nil, contact_email: "producer@marriotttheatre.com", casting_director: "Associate Artistic Director: Peter Marston Sullivan", casting_email: "Peter.Sullivan@MarriottTheatre.com", notes: nil, season_type: "Musicals ", union_status: "Non-Union?", image_url: nil, active: true},
#   {name: "MCA Stage", business_address_id: nil, performance_address_id: nil, website: "https://mcachicago.org/Programs/MCA-Stage", contact_name: nil, contact_email: "info@mcachicago.org", casting_director: nil, casting_email: nil, notes: "This is the museum of contemporary art", season_type: nil, union_status: nil, image_url: nil, active: true},
#   {name: "McAnich Arts Center", business_address_id: nil, performance_address_id: nil, website: "http://www.metropolisarts.com", contact_name: nil, contact_email: "info@metropolisarts.com", casting_director: "Casting: Robin Hughes", casting_email: "rhughes@metropolisarts.com", notes: "Also has performing arts school", season_type: nil, union_status: nil, image_url: nil, active: true},
#   {name: "Midsommer Flight", business_address_id: nil, performance_address_id: nil, website: "https://midsommerflight.com/", contact_name: nil, contact_email: "Contact form on website only thing available", casting_director: "Casting Director: Kanomé Jones", casting_email: nil, notes: nil, season_type: "Classical", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Mudlark Theater Company", business_address_id: nil, performance_address_id: nil, website: "http://www.mudlarktheater.org/", contact_name: "Andrew Biliter", contact_email: "headquarters@mudlarktheater.org", casting_director: "Artistic Director: Andrew Biliter", casting_email: "auditions@mudlarktheater.org", notes: "Children's theatre", season_type: "TYA", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Music Theater Works", business_address_id: nil, performance_address_id: nil, website: "https://www.musictheaterworks.com/", contact_name: "Kyle Dougan", contact_email: "info@musictheaterworks.org", casting_director: "Producing Artistic Director: Kyle Dougan", casting_email: "https://www.mtwcasting.com/", notes: "Formerly named Light Opera Works", season_type: "Musicals", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "North Riverside Players", business_address_id: nil, performance_address_id: nil, website: "http://www.nrplayers.com/", contact_name: "Unclear", contact_email: "Contact form on website only thing available", casting_director: nil, casting_email: nil, notes: "No real email or contact. You just fill out a form to get contacted", season_type: "Musicals/Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Northbrook Theatre", business_address_id: nil, performance_address_id: nil, website: "https://www.nbparks.org/programs/theatre/", contact_name: "Erin Sweet", contact_email: "esweet@nbparks.org", casting_director: "Erin Sweet", casting_email: "esweet@nbparks.org", notes: "Part of the parks district/community theatre program", season_type: "TYA; Theatre for Young Performers", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Northlight Theatre", business_address_id: nil, performance_address_id: nil, website: "www.northlight.org", contact_name: "BJ Jones", contact_email: "bjjones@northlight.org", casting_director: "Casting: Paskal Rudnicke Casting", casting_email: "EPA@northlight.org", notes: "Held digital EPAs this year: https://northlight.org/opportunities/", season_type: "Plays", union_status: "Equity", image_url: nil, active: true},
#   {name: "Nothing Without a Company", business_address_id: nil, performance_address_id: nil, website: "http://www.nothingwithoutacompany.org/", contact_name: "Anna Rose Ii-Epstein", contact_email: "AnnaRose@nothingwithoutacompany.org", casting_director: nil, casting_email: "casting@nothingwithoutacompany.org", notes: nil, season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Nuns4Fun Entertainment", business_address_id: nil, performance_address_id: nil, website: "https://nuns4fun.com/", contact_name: "Vicki Quade", contact_email: "vickiq@aol.com", casting_director: nil, casting_email: nil, notes: "Specializes in one woman religious comedies", season_type: "Comedies", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Oak Park Festival Theatre", business_address_id: nil, performance_address_id: nil, website: "www.oakparkfestival.com", contact_name: "Barbara Zahora", contact_email: "festival@oakparkfestival.com", casting_director: "Casting Director: Lucy Carr", casting_email: "Lucy@oakparkfestival.com", notes: nil, season_type: "Plays, Shakespeare, Classics", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Oakton Community College Performing Arts Center", business_address_id: nil, performance_address_id: nil, website: "https://www.oakton.edu/about/thearts/performing_arts_center/", contact_name: "John Frisco", contact_email: "jfrisco@oakton.edu", casting_director: nil, casting_email: "https://www.oakton.edu/about/thearts/performing_arts_center/auditions/audition.pdf", notes: nil, season_type: "Musicals; Plays; Improv", union_status: "non-Equity", image_url: nil, active: true},
#   {name: "Oil Lamp Theater", business_address_id: nil, performance_address_id: nil, website: "https://oillamptheater.org/", contact_name: nil, contact_email: "info@oillamptheater.org", casting_director: "Associate Artistic Director: Stephen Smith", casting_email: "stephen@oillamptheater.org", notes: "They seem to do It's A Wonderful Life every year", season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Open Door Repertory", business_address_id: nil, performance_address_id: nil, website: "https://www.opendoortheater.net/", contact_name: "Mary Pat Seick", contact_email: "opendoor902@gmail.com", casting_director: nil, casting_email: nil, notes: nil, season_type: "Musicals; Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Organic Theater Company", business_address_id: nil, performance_address_id: nil, website: "http://organictheater.org/", contact_name: "Alex Gelman", contact_email: "info@organictheater.org", casting_director: "Sara Copeland", casting_email: nil, notes: nil, season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Otherworld Theatre Company", business_address_id: nil, performance_address_id: nil, website: "https://www.otherworldtheatre.org/", contact_name: nil, contact_email: "info@otherworldtheatre.org", casting_director: nil, casting_email: nil, notes: "Also offers space rentals", season_type: nil, union_status: nil, image_url: nil, active: true},
#   {name: "Paramount Theatre", business_address_id: nil, performance_address_id: nil, website: "https://paramountaurora.com/", contact_name: "Jim Corti", contact_email: "info@paramountarts.com", casting_director: "Broadway Series Casting Director: Trent Stork", casting_email: "casting@paramountarts.com", notes: "Trying to open new space for Stage Plays", season_type: "Musicals, New Works; Plays", union_status: "Equity", image_url: nil, active: true},
#   {name: "Passage Theatre, The", business_address_id: nil, performance_address_id: nil, website: "https://www.thepassagetheatre.com/", contact_name: "Grace Bolander/Kevin Minor", contact_email: "grace.bolander@thepassagetheatre.com", casting_director: "Casting Director: Ben F. Locke", casting_email: "ben.locke@thepassagetheatre.com", notes: nil, season_type: "Experimental Plays; New Works", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Pegasus Theatre Chicago", business_address_id: nil, performance_address_id: nil, website: "http://pegasustheatrechicago.org/", contact_name: nil, contact_email: "info@pegasustheatrechicago.org", casting_director: nil, casting_email: "casting@pegasustheatrechicago.org", notes: "Annual Young Playwright's Festical", season_type: "Plays; Readings", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Petite Opera Productions", business_address_id: nil, performance_address_id: nil, website: "https://petiteopera.org/", contact_name: nil, contact_email: "info@petiteopera.org", casting_director: nil, casting_email: "auditions@petiteopera.org", notes: nil, season_type: "Musicals,Operas", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Physical Theater Festival", business_address_id: nil, performance_address_id: nil, website: "https://www.physicalfestival.com/", contact_name: "Alice da Cuna and Marc Frost", contact_email: "info@physicalfestival.com", casting_director: nil, casting_email: nil, notes: "Accepts submissions of physical theatre plays from companies", season_type: "Plays, Physical Theatre, New works", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Piven Theatre Workshop", business_address_id: nil, performance_address_id: nil, website: "https://www.piventheatre.org/", contact_name: nil, contact_email: "info@piventheatre.org", casting_director: nil, casting_email: "Piven Theatre 927 Noyes St. #110 Evanston, IL 60201 ATTN: Casting", notes: "Mainly a training center", season_type: nil, union_status: nil, image_url: nil, active: true},
#   {name: "Pivot Arts", business_address_id: nil, performance_address_id: nil, website: "https://pivotarts.org/", contact_name: "Julieanne Ehre", contact_email: "info@pivotarts.org", casting_director: nil, casting_email: nil, notes: "Multidiscplinary, site specific and interactive performance tours", season_type: "Plays, New Works, Contemporary ", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "PlayMakers Laboratory Theatre", business_address_id: nil, performance_address_id: nil, website: "https://www.playmakerslab.org/", contact_name: "Colette Gregory", contact_email: "cgregory@playmakerslab.org", casting_director: nil, casting_email: nil, notes: "773 506-7140", season_type: "Theatre for Young Performers", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Porchlight Music Theatre", business_address_id: nil, performance_address_id: nil, website: "https://porchlightmusictheatre.org/", contact_name: "Michael Weber", contact_email: "info@porchlightmusictheatre.org", casting_director: "Christopher Pazdernik", casting_email: "auditions@porchlightmusictheatre.org", notes: "773-777-9884", season_type: "Musicals", union_status: "Equity", image_url: nil, active: true},
#   {name: "Pride Films and Plays", business_address_id: nil, performance_address_id: nil, website: "http://pridefilmsandplays.com/", contact_name: "Was Donterrio Johnson but he recently stepped down", contact_email: "pridefilmsandplays@gmail.com", casting_director: nil, casting_email: nil, notes: "773-857-0222 Probably gonna close", season_type: "Plays;Musicals", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Promethean Theatre Ensemble", business_address_id: nil, performance_address_id: nil, website: "www.prometheantheatre.org", contact_name: "Nicole Hand", contact_email: "info@prometheantheatre.org", casting_director: "Casting Director: Anne Lentino", casting_email: "casting@prometheantheatre.org", notes: nil, season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Prop Thtr", business_address_id: nil, performance_address_id: nil, website: "https://www.propthtr.org/", contact_name: "Olivia Lilley", contact_email: "Contact form on website only thing available", casting_director: nil, casting_email: nil, notes: " They just lost their performance space", season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Raven Theatre Company", business_address_id: nil, performance_address_id: nil, website: "https://www.raventheatre.com/", contact_name: "Cody Estle", contact_email: "info@raventheatre.com", casting_director: nil, casting_email: "info@raventheatre.com", notes: "(773) 338-2177", season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Red Tape Theatre Company", business_address_id: nil, performance_address_id: nil, website: "https://redtapetheatre.org/", contact_name: "Max Truax", contact_email: " max.truax@redtapetheatre.org ", casting_director: nil, casting_email: "casting@redtapetheatre.org", notes: nil, season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Red Theater Chicago", business_address_id: nil, performance_address_id: nil, website: "https://redtheater.org/", contact_name: "Wyatt Kent", contact_email: "wyattkent@redtheater.org", casting_director: "Becca Holloway", casting_email: "casting@redtheater.org", notes: "They're currently looking for a new ED and Production Manager", season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Redtwist Theatre", business_address_id: nil, performance_address_id: nil, website: "www.redtwist.org", contact_name: "Charlie Marie McGrath", contact_email: "reserve@redtwist.org", casting_director: "Casting Director: Julia Skeggs", casting_email: "reserve@redtwist.org", notes: "(773) 728-7529", season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Theo Ubique Cabaret Theatre", business_address_id: nil, performance_address_id: nil, website: "https://www.theo-u.com/", contact_name: nil, contact_email: "artisticdirector@theo-u.org, managingdirector@theo-u.org, marketing@theo-u.org, media@theo-u.org", casting_director: nil, casting_email: nil, notes: "(773) 347-1109", season_type: "Musicals", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Remy Bumppo Theatre Company", business_address_id: nil, performance_address_id: nil, website: "www.remybumppo.org", contact_name: "Nick Sandys", contact_email: "SUBMIT FORM: https://www.remybumppo.org/contact/", casting_director: "Casting Director: Linda Gillum", casting_email: nil, notes: "You can mail in your headshot resume to them", season_type: "Plays, Classics, Adaptations", union_status: "Equity", image_url: nil, active: true},
#   {name: "Rivendell Theatre Ensemble", business_address_id: nil, performance_address_id: nil, website: "https://rivendelltheatre.org/", contact_name: "Tara Mallen", contact_email: "info@rivendelltheatre.org", casting_director: "Ashley Neal", casting_email: "casting@rivendelltheatre.org", notes: "(773) 334-7728 They only do invited auditions and by appointment only", season_type: "Plays, Female Centered", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Rose Valley Theatre Group", business_address_id: nil, performance_address_id: nil, website: "http://magurabcs.com/English", contact_name: nil, contact_email: "magurabcs@gmail.com", casting_director: nil, casting_email: nil, notes: "(224) 800-1538 The website is not in English and very confusing", season_type: nil, union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Saint Sebastian Players", business_address_id: nil, performance_address_id: nil, website: "http://saintsebastianplayers.org/", contact_name: nil, contact_email: "info@saintsebastianplayers.org", casting_director: nil, casting_email: "info@saintsebastianplayers.org", notes: nil, season_type: "Plays; Musicals", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Saltbox Theatre Collective", business_address_id: nil, performance_address_id: nil, website: "http://www.saltboxtheatre.org/", contact_name: "Brian Fruits", contact_email: "Info@Saltboxtheatre.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Shattered Globe Theatre", business_address_id: nil, performance_address_id: nil, website: "www.sgtheatre.org", contact_name: nil, contact_email: "info@shatteredglobe.org, david@drpublicrelations.com", casting_director: "Casting Director: Doug McDade", casting_email: "casting@shatteredglobe.org", notes: "773-770-0333", season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Sideshow Theatre Company", business_address_id: nil, performance_address_id: nil, website: "https://www.sideshowtheatre.org/", contact_name: "Regina Victor", contact_email: "sideshow@sideshowtheatre.org", casting_director: "Aimee Caron", casting_email: "aimee@sideshowtheatre.org", notes: nil, season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Silk Road Rising", business_address_id: nil, performance_address_id: nil, website: "www.silkroadrising.org", contact_name: "MALIK GILLANI", contact_email: "info@silkroadrising.org", casting_director: "Casting Director: Claire Simon Casting", casting_email: nil, notes: "312.857.1234 Emphasizes Asian, Middle Eastern and Muslim experiences", season_type: "Plays", union_status: "Equity", image_url: nil, active: true},
#   {name: "Skokie Park District Devonshire Playhouse", business_address_id: nil, performance_address_id: nil, website: "https://www.skokieparks.org/devonshire-playhouse/", contact_name: " Robin Horwitz", contact_email: "rhhorwitz@skokieparks.org", casting_director: "Robin Horwitz", casting_email: "rhhorwitz@skokieparks.org", notes: "847-674-1500, ext. 2400", season_type: "Musicals; Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Something Marvelous", business_address_id: nil, performance_address_id: nil, website: "http://www.somethingmarvelous.org/", contact_name: "Emmi Hilger", contact_email: "festival@somethingmarvelous.org", casting_director: "Casting Directors: Cruz Gonzalez-Cadel", casting_email: "festival@somethingmarvelous.org", notes: nil, season_type: "Plays, New Works", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Stage Left Theatre", business_address_id: nil, performance_address_id: nil, website: "https://www.stagelefttheatre.com/", contact_name: nil, contact_email: "press@stagelefttheatre.com", casting_director: "Casting Director: Brittany Gillespie", casting_email: nil, notes: "(773) 649-3186", season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Steppenwolf Theatre Company", business_address_id: nil, performance_address_id: nil, website: "www.steppenwolf.org", contact_name: nil, contact_email: "mlong@steppenwolf.org, customerservice@steppenwolf.org", casting_director: "Casting Director: JC Clementz", casting_email: nil, notes: "(312) 335-1650", season_type: "Plays", union_status: "Equity", image_url: nil, active: true},
#   {name: "Stockyards Theatre Project", business_address_id: nil, performance_address_id: nil, website: "http://www.stockyardstheatreproject.org/index.html", contact_name: nil, contact_email: "stockyards@stockyardstheatreproject.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Plays, New Works ", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Strawdog Theatre Company", business_address_id: nil, performance_address_id: nil, website: "www.strawdog.org", contact_name: nil, contact_email: "Site Under Maintenance", casting_director: nil, casting_email: nil, notes: "773.644.1380", season_type: "Plays, Classical, Contemporary, New Works", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Teatro Vista", business_address_id: nil, performance_address_id: nil, website: "https://www.teatrovista.org/", contact_name: nil, contact_email: "info@teatrovista.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Plays, Classical, Contemporary, New Works; LatinX Centered ", union_status: "Equity", image_url: nil, active: true},
#   {name: "The Artistic Home", business_address_id: nil, performance_address_id: nil, website: "https://www.theartistichome.org/", contact_name: nil, contact_email: "john@johnolsoncomm.com", casting_director: nil, casting_email: "artistichomecasting@gmail.com", notes: "(312) 243-3963", season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "The Barrens Theatre Co", business_address_id: nil, performance_address_id: nil, website: "https://www.thebarrenstheatreco.com/", contact_name: nil, contact_email: "barrenstheatreco@gmail.com", casting_director: nil, casting_email: nil, notes: nil, season_type: "Avante Garde, Devised Work, Immersive", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "The Cuckoo's Theater", business_address_id: nil, performance_address_id: nil, website: "TheCuckoosTheaterProject.com", contact_name: nil, contact_email: "Info@TheCuckoosTheaterProject.com", casting_director: nil, casting_email: nil, notes: "312-882-8201", season_type: "Plays", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "The Gift Theatre", business_address_id: nil, performance_address_id: nil, website: "thegifttheatre.org", contact_name: nil, contact_email: "GiftBoxOffice@gmail.com, development@TheGiftTheatre.org", casting_director: "Casting Director: Emjoy Gavino", casting_email: nil, notes: "(773) 283-7071", season_type: "Plays, Classical, Contemporary, New Works", union_status: "Equity", image_url: nil, active: true},
#   {name: "The House Theatre of Chicago", business_address_id: nil, performance_address_id: nil, website: "www.thehousetheatre.com", contact_name: nil, contact_email: "info@thehousetheatre.com", casting_director: "Casting Director: Marika Mashburn", casting_email: nil, notes: "(773) 769-3832", season_type: "Plays; Classical, Contemporary; Musicals", union_status: "Equity", image_url: nil, active: true},
#   {name: "The Impostors Theatre", business_address_id: nil, performance_address_id: nil, website: "https://theimpostorstheatre.com/whoweare.html", contact_name: nil, contact_email: "impostorstheatre@gmail.com, impostorstheatre.marketing@gmail.com, impostorstheatre.development@gmail.com", casting_director: nil, casting_email: nil, notes: nil, season_type: "Plays; Contemporary, New Works; Avante Garde, Devised Work, Immersive", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "The Joffrey Ballet", business_address_id: nil, performance_address_id: nil, website: "http://joffrey.org/", contact_name: nil, contact_email: "SUBMIT FORM: http://joffrey.org/contact", casting_director: nil, casting_email: nil, notes: "(312) 386-8905", season_type: "Dance, Ballet ", union_status: "AGMA", image_url: nil, active: true},
#   {name: "The Neo-Futurists", business_address_id: nil, performance_address_id: nil, website: "https://neofuturists.org/", contact_name: nil, contact_email: "artistic@neofuturists.org", casting_director: nil, casting_email: nil, notes: "(773) 878-4557", season_type: "Avante Garde; Devised, Immersive ", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "The New Colony", business_address_id: nil, performance_address_id: nil, website: "http://thenewcolony.org/ ", contact_name: nil, contact_email: nil, casting_director: nil, casting_email: nil, notes: "Website under construction", season_type: "Plays, New Works ", union_status: nil, image_url: nil, active: true},
#   {name: "The Plagiarists", business_address_id: nil, performance_address_id: nil, website: "https://www.theplagiarists.org/", contact_name: nil, contact_email: "info@theplagiarists.org, sara@theplagiarists.org, emma@theplagiarists.org", casting_director: nil, casting_email: nil, notes: "(773) 599-9490", season_type: "Plays, New Works; Avante Garde, Devised", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "The Revival", business_address_id: nil, performance_address_id: nil, website: "https://www.the-revival.com/home", contact_name: nil, contact_email: "SUBMIT FORM: https://www.the-revival.com/contact-us?rq=contact", casting_director: "Executive Director: John Stoops", casting_email: nil, notes: nil, season_type: "Comedy ", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "The Rising Stars Theatre Co.", business_address_id: nil, performance_address_id: nil, website: "http://www.risingstarschicago.com/", contact_name: nil, contact_email: "risingstarstc@gmail.com", casting_director: nil, casting_email: nil, notes: "(773) 736-2490", season_type: "Theatre by Young Performers; Musicals ", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "The Second City", business_address_id: nil, performance_address_id: nil, website: "https://www.secondcity.com/new-online-improv-offerings", contact_name: nil, contact_email: "SUBMIT FORM: https://www.secondcity.com/contact/", casting_director: nil, casting_email: nil, notes: "(312) 662-4562", season_type: "Comedy", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "The Side Project", business_address_id: nil, performance_address_id: nil, website: "http://thesideproject.net/current.php", contact_name: nil, contact_email: "CLOSEST OPTION: production@thesideproject.net", casting_director: nil, casting_email: nil, notes: "773-340-0140", season_type: "Plays ", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "The Trance", business_address_id: nil, performance_address_id: nil, website: "https://trancetheatrepoetrydance.net/", contact_name: nil, contact_email: "SUBMIT FORM: https://trancetheatrepoetrydance.net/contact/", casting_director: nil, casting_email: nil, notes: nil, season_type: "Avante Garde, Devised, Physical Theatre; Dance", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Theater Oobleck", business_address_id: nil, performance_address_id: nil, website: "https://theateroobleck.com/home/", contact_name: nil, contact_email: "david@theateroobleck.com", casting_director: nil, casting_email: nil, notes: "(773) 897-5089", season_type: "Plays, New Works; Avante Garde, Devised", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Theater Wit", business_address_id: nil, performance_address_id: nil, website: "www.theatrewit.org", contact_name: nil, contact_email: "info@theaterwit.org", casting_director: "Casting: Jeremy Wechsler", casting_email: nil, notes: "(773) 975-8150", season_type: "Plays ", union_status: "Equity", image_url: nil, active: true},
#   {name: "Theatre Above The Law", business_address_id: nil, performance_address_id: nil, website: "https://www.theatreatl.org/", contact_name: nil, contact_email: "theatre.atl.casting@gmail.com", casting_director: "Casting: Brittany Vogel", casting_email: nil, notes: "(773) 655-7197", season_type: "Plays; Theatre By Young Performers", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Theatre Evolve", business_address_id: nil, performance_address_id: nil, website: "www.theatreevolve.com", contact_name: nil, contact_email: "Theatreevolve@gmail.com", casting_director: nil, casting_email: nil, notes: "WHO ARE THESE NERDS?!?!?!?!?!?!", season_type: "Plays ", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Theatre Y", business_address_id: nil, performance_address_id: nil, website: "theatre-y.com", contact_name: nil, contact_email: "info@theatre-y.com", casting_director: nil, casting_email: nil, notes: "708-209-0183", season_type: "Avante Garde, Devised, Physical Theatre ", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "TimeLine Theatre Company", business_address_id: nil, performance_address_id: nil, website: "www.timelinetheatre.com", contact_name: nil, contact_email: "info@timelinetheatre.com", casting_director: "Casting: Director: Nick Bowling", casting_email: "casting@timelinetheatre.com", notes: "(773) 281-8463", season_type: "Plays, Contemporary, New Works ", union_status: "Equity", image_url: nil, active: true},
#   {name: "Trap Door Theatre", business_address_id: nil, performance_address_id: nil, website: "http://trapdoortheatre.com/", contact_name: nil, contact_email: "boxofficetrapdoor@gmail.com", casting_director: nil, casting_email: "trapdoorcasting@gmail.com", notes: "(773) 384-0494", season_type: "Plays; Avante Garde ", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Underscore Theatre Company", business_address_id: nil, performance_address_id: nil, website: "https://www.underscoretheatre.org/", contact_name: nil, contact_email: "Rachel.Johnson@UnderscoreTheatre.org, Brendan@UnderscoreTheatre.org, Katy.Campbell@UnderscoreTheatre.org, Solana.Oliver@UnderscoreTheatre.org", casting_director: nil, casting_email: "casting@underscoretheatre.org", notes: "(312) 646-0975", season_type: "Musicals", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "UrbanTheater Company", business_address_id: nil, performance_address_id: nil, website: "https://urbantheaterchicago.org/", contact_name: nil, contact_email: "info@urbantheaterchicago.org", casting_director: nil, casting_email: nil, notes: "(312) 767-8821", season_type: "Plays; LatinX Centered ", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Valiant Theatre", business_address_id: nil, performance_address_id: nil, website: "https://www.valianttheatre.org/", contact_name: nil, contact_email: "administration@valianttheatre.org", casting_director: "Casting: Becca Braun", casting_email: "casting@valianttheatre.org", notes: "773-774-0677", season_type: "Plays ", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Victory Gardens Theater", business_address_id: nil, performance_address_id: nil, website: "www.victorygardens.org", contact_name: nil, contact_email: "information@victorygardens.org", casting_director: "Casting Director: Kanome Jones", casting_email: "casting@victorygardens.org", notes: "773.871.3000", season_type: "Plays, Contemporary, New Works ", union_status: "Equity", image_url: nil, active: true},
#   {name: "Walkabout Theater", business_address_id: nil, performance_address_id: nil, website: "http://walkabouttheater.org/", contact_name: nil, contact_email: "admin@walkabouttheater.org", casting_director: nil, casting_email: nil, notes: nil, season_type: "Avante Garde, Devised, Physical Theatre, Immersive", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Water People Theater", business_address_id: nil, performance_address_id: nil, website: "https://waterpeople.org/", contact_name: nil, contact_email: "info@waterpeople.org", casting_director: nil, casting_email: nil, notes: "(312) 473-7970", season_type: "Plays; LatinX Centered ", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "WildClaw Theatre", business_address_id: nil, performance_address_id: nil, website: "http://www.wildclawtheatre.com/", contact_name: nil, contact_email: "http://www.wildclawtheatre.com/contact/", casting_director: nil, casting_email: nil, notes: nil, season_type: "Plays; Horror", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Williams Street Repertory", business_address_id: nil, performance_address_id: nil, website: "http://wsrep.org/", contact_name: nil, contact_email: "YouthCasting@wsrep.org", casting_director: nil, casting_email: "casting@wsrep.org", notes: "(815) 356-9212", season_type: "Plays, Musicals", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Wilmette Children's Theatre", business_address_id: nil, performance_address_id: nil, website: "http://www.wilmettepark.org/theater", contact_name: nil, contact_email: "adornheggen@wilpark.org", casting_director: nil, casting_email: nil, notes: "847-256-6100", season_type: "Theatre for Young Performances", union_status: "Non-Equity", image_url: nil, active: true},
#   {name: "Windy City Playhouse", business_address_id: nil, performance_address_id: nil, website: "https://windycityplayhouse.com/", contact_name: nil, contact_email: "info@windycityplayhouse.com", casting_director: "Casting Director: Samantha Mitchell", casting_email: nil, notes: nil, season_type: "Plays; Musicals", union_status: "Equity", image_url: nil, active: true},
#   {name: "Writers Theatre", business_address_id: nil, performance_address_id: nil, website: "www.writerstheatre.org", contact_name: nil, contact_email: "boxoffice@writerstheatre.org", casting_director: "Casting Director: Geoff Button", casting_email: nil, notes: nil, season_type: "Plays, Classical, Contemporary; Musicals ", union_status: "Equity", image_url: nil, active: true}
# ])
# Address.create!([
#   {address1: "1925 W. Cullom Ave", address2: "Apt 1", address3: nil, city: "Chicago", state: "IL", country: "US", postal_code: "60613"},
#   {address1: "2515 Central Park Ave", address2: nil, address3: nil, city: " Evanston", state: " IL", country: nil, postal_code: " 60201"},
#   {address1: "1531 N Wells St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60610"},
#   {address1: "5252 N Broadway", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60640"},
#   {address1: "1012 N Noble St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60642"},
#   {address1: "2707 N Laramie Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60639"},
#   {address1: "851 W Belmont Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60657"},
#   {address1: "2540 N Lincoln Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60614"},
#   {address1: "2407 W 111th St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60655"},
#   {address1: "2153 W 111th St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60643"},
#   {address1: "4450 N Clark St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60640"},
#   {address1: "340 W Diversey Pkwy #1717", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60657"},
#   {address1: "2257 N Lincoln Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60614"},
#   {address1: "P.O. Box 607782", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60660"},
#   {address1: "1331 N Milwaukee Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60622"},
#   {address1: "425 Fawell Blvd", address2: nil, address3: nil, city: " Glen Ellyn", state: " IL", country: nil, postal_code: " 60137"},
#   {address1: "100 S Racine Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60607"},
#   {address1: "1650 W Foster Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60640"},
#   {address1: "1105 W Chicago Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60642"},
#   {address1: "330 202nd St", address2: nil, address3: nil, city: " Chicago Heights", state: " IL", country: nil, postal_code: " 60411"},
#   {address1: "70 E Lake St UNIT 415", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60601"},
#   {address1: "800 E Grand Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60611"},
#   {address1: "220 S Michigan Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60604"},
#   {address1: "​​641 W Lake Street Suite 200", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60661"},
#   {address1: "620 Lincoln Ave", address2: nil, address3: nil, city: " Winnetka", state: " IL", country: nil, postal_code: " 60093"},
#   {address1: "300 S Waukegan Rd", address2: nil, address3: nil, city: " Lake Forest", state: " IL", country: nil, postal_code: " 60045"},
#   {address1: "1020 W Bryn Mawr Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60660"},
#   {address1: "1579 N Milwaukee Ave #336", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60622"},
#   {address1: "4001 N Ravenswood Ave #110", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60613"},
#   {address1: "4001 N Ravenswood Ave #405", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60613"},
#   {address1: "1016 N Dearborn St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60610"},
#   {address1: "4210 N Lincoln Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60618"},
#   {address1: "5535 S Ellis Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60637"},
#   {address1: "100 Drury Lane", address2: nil, address3: nil, city: " Oakbrook Terrace", state: " IL", country: nil, postal_code: " 60181"},
#   {address1: "4001 N Ravenswood Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60613"},
#   {address1: "6736 N Loleta Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60646"},
#   {address1: "1623 Howard St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60626"},
#   {address1: "4041 N Milwaukee Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60641"},
#   {address1: "1717 31st St", address2: nil, address3: nil, city: " Oak Brook", state: " IL", country: nil, postal_code: " 60523"},
#   {address1: "927 Noyes St", address2: nil, address3: nil, city: " Evanston", state: " IL", country: nil, postal_code: " 60201"},
#   {address1: "1419 W Blackhawk St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60642"},
#   {address1: "449 W Kenilworth Ave", address2: nil, address3: nil, city: " Palatine", state: " IL", country: nil, postal_code: " 60067"},
#   {address1: "4453 N Albany Ave #1S", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60625"},
#   {address1: "925 Ohio St", address2: nil, address3: nil, city: " Lisle", state: " IL", country: nil, postal_code: " 60532"},
#   {address1: "170 N Dearborn St.", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60601"},
#   {address1: "5301 North Damen Avenue", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60625"},
#   {address1: "2233 S Throop", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60608"},
#   {address1: "1147 W Jackson Blvd", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60607"},
#   {address1: "2025 W Chase Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60645"},
#   {address1: "2519 N California Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60647"},
#   {address1: "5315 N. Clark St #142", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60640"},
#   {address1: "1106 W Thorndale Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60660"},
#   {address1: "3801 S Central Ave", address2: nil, address3: nil, city: " Cicero", state: " IL", country: nil, postal_code: " 60804"},
#   {address1: "14200 S CLUB RIDGE CIR UNIT 101", address2: nil, address3: nil, city: " Lockport", state: " IL", country: nil, postal_code: " 60441-4992"},
#   {address1: "20 N Upper Wacker Dr", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60606"},
#   {address1: "1010 Madison St", address2: nil, address3: nil, city: " Oak Park", state: " IL", country: nil, postal_code: " 60302"},
#   {address1: "1342 Barclay Blvd", address2: nil, address3: nil, city: " Buffalo Grove", state: " IL", country: nil, postal_code: " 60089"},
#   {address1: "1417 Hinman Ave", address2: nil, address3: nil, city: " Evanston", state: " IL", country: nil, postal_code: " 60201"},
#   {address1: "516 4th Street", address2: nil, address3: nil, city: " Wilmette", state: " IL", country: nil, postal_code: " 60091"},
#   {address1: "2401 S. Des Plaines Ave.", address2: nil, address3: nil, city: " North Riverside", state: " IL", country: nil, postal_code: nil},
#   {address1: "3323 Walters Ave", address2: nil, address3: nil, city: " Northbrook", state: " IL", country: nil, postal_code: " 60062"},
#   {address1: "9501 Skokie Blvd", address2: nil, address3: nil, city: " Skokie", state: " IL", country: nil, postal_code: " 60077"},
#   {address1: "1008 WEST ARGYLE STREET #2E", address2: nil, address3: nil, city: " CHICAGO", state: " IL", country: nil, postal_code: " 60640"},
#   {address1: "4343 N Clarendon Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60613"},
#   {address1: "P.O. Box 4114", address2: nil, address3: nil, city: " Oak Park", state: " IL", country: nil, postal_code: " 60303"},
#   {address1: "1723 Glenview Rd", address2: nil, address3: nil, city: " Glenview", state: " IL", country: nil, postal_code: " 60025"},
#   {address1: "902 S Ridgeland Ave", address2: nil, address3: nil, city: " Oak Park", state: " IL", country: nil, postal_code: " 60304"},
#   {address1: "P.O. Box 257603", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60625"},
#   {address1: "1105 W Chicago Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60642"},
#   {address1: "1658 N. Milwaukee Ave. Suite 374", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60647"},
#   {address1: "5252 N. Broadway Avenue 2nd floor", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60640"},
#   {address1: "4021 N Broadway. FL 1", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60613"},
#   {address1: "1016 N. Dearborn St.", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60610"},
#   {address1: "4139 N Broadway", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60613"},
#   {address1: "4147 N Broadway", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60613"},
#   {address1: "1224 W. Farwell Ave. 1N", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60626"},
#   {address1: "3502 N. Elston Avenue", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60618"},
#   {address1: "6157 N Clark St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60660"},
#   {address1: "4546 N Western Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60625"},
#   {address1: "1044 W Bryn Mawr Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60660"},
#   {address1: "3717 N. Ravenswood Ave Suite 237", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60613"},
#   {address1: "5779 N Ridge Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60660"},
#   {address1: "415 W Golf Rd # 7", address2: nil, address3: nil, city: " Arlington Heights", state: " IL", country: nil, postal_code: " 60005"},
#   {address1: "1625 W Diversey Pkwy", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60614"},
#   {address1: "2936 N. Southport Ave. Suite 214", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60657"},
#   {address1: "PO Box 409360", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60640"},
#   {address1: "77 W Washington St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60602"},
#   {address1: "4400 Greenwood Street", address2: nil, address3: nil, city: " Skokie", state: " IL", country: nil, postal_code: " 60076"},
#   {address1: "111 N Wabash Ave Suite 2005", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60602"},
#   {address1: "1115 W Berwyn Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60640"},
#   {address1: "1650 N Halsted St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60614"},
#   {address1: "6549 N. Ashland Ave. 1-S", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60626"},
#   {address1: "2936 N Southport Ave UNIT 210", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60657"},
#   {address1: "32 W Randolph St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60601"},
#   {address1: "1376 W Grand Ave. #7761", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60642"},
#   {address1: "7077 N Ashland", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60626"},
#   {address1: "4802 N Milwaukee Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60630"},
#   {address1: "4020 N Rockwell St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60618"},
#   {address1: "1579 N. Milwaukee Ave.", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60622"},
#   {address1: "10 E Randolph St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60601"},
#   {address1: "5153 N Ashland Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60640"},
#   {address1: "1333 N Milwaukee Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60622"},
#   {address1: "P.O. Box 578545", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60657"},
#   {address1: "PO Box 607666", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60660-7666"},
#   {address1: "1522 W Sunnyside Ave Apt 2ES", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60657"},
#   {address1: "6826 N. Wayne Ave 3C", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60626"},
#   {address1: "223 W Ohio St suite c", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60654"},
#   {address1: "2515 Central Park Ave.", address2: nil, address3: nil, city: " Evanston", state: " IL", country: nil, postal_code: nil},
#   {address1: "1105 W Chicago Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60642"},
#   {address1: "330 202nd St", address2: nil, address3: nil, city: " Chicago Heights", state: " IL", country: nil, postal_code: " 60411"},
#   {address1: "410 S Michigan Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60605"},
#   {address1: "800 E Grand Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60611"},
#   {address1: "220 S Michigan Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60604"},
#   {address1: "620 Lincoln Ave", address2: nil, address3: nil, city: " Winnetka", state: " IL", country: nil, postal_code: " 60093"},
#   {address1: "300 S Waukegan Rd", address2: nil, address3: nil, city: " Lake Forest", state: " IL", country: nil, postal_code: " 60045"},
#   {address1: "1020 W Bryn Mawr Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60660"},
#   {address1: "1579 N Milwaukee Ave #336", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60622"},
#   {address1: "1016 N Dearborn St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60610"},
#   {address1: "4210 N Lincoln Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60618"},
#   {address1: "182 N Wabash Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60601"},
#   {address1: "100 Drury Lane", address2: nil, address3: nil, city: " Oakbrook Terrace", state: " IL", country: nil, postal_code: " 60181"},
#   {address1: "927 Noyes St", address2: nil, address3: nil, city: " Evanston", state: " IL", country: nil, postal_code: " 60201"},
#   {address1: "Theater Wit: 1229 W Belmont Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60657"},
#   {address1: "3253 W. Wilson Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60625"},
#   {address1: "1331 N Milwaukee Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60622"},
#   {address1: "735 N Milwaukee Ave", address2: nil, address3: nil, city: " Libertyville", state: " IL", country: nil, postal_code: nil},
#   {address1: "5917 N Broadway Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60660"},
#   {address1: "1229 W Belmont Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60657"},
#   {address1: "6912 N Glenwood Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60626"},
#   {address1: "821 N Michigan Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60611"},
#   {address1: "7924 Lincoln Ave", address2: nil, address3: nil, city: " Skokie", state: " IL", country: nil, postal_code: " 60077"},
#   {address1: "10 Marriott Drive", address2: nil, address3: nil, city: " Lincolnshire", state: " IL", country: nil, postal_code: " 60069"},
#   {address1: "111 W Campbell St", address2: nil, address3: nil, city: " Arlington Heights", state: " IL", country: nil, postal_code: " 60005"},
#   {address1: "1417 Hinman Ave", address2: nil, address3: nil, city: " Evanston", state: " IL", country: nil, postal_code: " 60201"},
#   {address1: "927 Noyes St.", address2: nil, address3: nil, city: " Evanston", state: " IL", country: nil, postal_code: " 60201"},
#   {address1: "3323 Walters Ave", address2: nil, address3: nil, city: " Northbrook", state: " IL", country: nil, postal_code: " 60062"},
#   {address1: "9501 Skokie Blvd", address2: nil, address3: nil, city: " Skokie", state: " IL", country: nil, postal_code: " 60077"},
#   {address1: "1641 N. Halsted", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60614"},
#   {address1: "167 Forest Ave", address2: nil, address3: nil, city: " Oak Park", state: " IL", country: nil, postal_code: " 60301"},
#   {address1: "1600 Golf Rd", address2: nil, address3: nil, city: " Des Plaines", state: " IL", country: nil, postal_code: " 60016"},
#   {address1: "1723 Glenview Rd", address2: nil, address3: nil, city: " Glenview", state: " IL", country: nil, postal_code: " 60025"},
#   {address1: "902 S Ridgeland Ave", address2: nil, address3: nil, city: " Oak Park", state: " IL", country: nil, postal_code: " 60304"},
#   {address1: "3914 N Clark St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60613"},
#   {address1: "23 E Galena Blvd", address2: nil, address3: nil, city: " Aurora", state: " IL", country: nil, postal_code: " 60506"},
#   {address1: "306 S Prospect Ave", address2: nil, address3: nil, city: " Park Ridge", state: " IL", country: nil, postal_code: " 60068"},
#   {address1: "1229 W Belmont Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60657"},
#   {address1: "927 Noyes St", address2: nil, address3: nil, city: " Evanston", state: " IL", country: nil, postal_code: " 60201"},
#   {address1: "1016 N. Dearborn St.", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60610"},
#   {address1: "6157 N Clark St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60660"},
#   {address1: "4546 N Western Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60625"},
#   {address1: "1044 W Bryn Mawr", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60660"},
#   {address1: "5779 N Ridge Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60660"},
#   {address1: "1229 W Belmont Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60657"},
#   {address1: "1160 E 55th St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60615"},
#   {address1: "6850 W Addison St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60634"},
#   {address1: "230 W North Ave 3rd Floor", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60614"},
#   {address1: "1439 W Jarvis Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60626"},
#   {address1: "1229 W Belmont Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60657"},
#   {address1: "1439 W Jarvis Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60626"},
#   {address1: "4546 N Western Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60625"},
#   {address1: "721 Howard St", address2: nil, address3: nil, city: " Evanston", state: " IL", country: nil, postal_code: " 60202"},
#   {address1: "115 N Genesee St", address2: nil, address3: nil, city: " Waukegan", state: " IL", country: nil, postal_code: " 60085"},
#   {address1: "615 W Wellington Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60657"},
#   {address1: "1655 W Cortland St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60622"},
#   {address1: "4609 N Clark St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60640"},
#   {address1: "2620 W Division St", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60622"},
#   {address1: "2433 N Lincoln Ave", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60614"},
#   {address1: "5555 N Sheridan Rd #610", address2: nil, address3: nil, city: " Chicago", state: " IL", country: nil, postal_code: " 60640"},
#   {address1: "26 N Williams St", address2: nil, address3: nil, city: " Crystal Lake", state: " IL", country: nil, postal_code: " 60014"},
#   {address1: "3000 Glenview Road", address2: nil, address3: nil, city: " Wilmette", state: " IL", country: nil, postal_code: " 60091"},
#   {address1: "325 Tudor Ct", address2: nil, address3: nil, city: " Glencoe", state: " IL", country: nil, postal_code: " 60022"}
# ])
